import type { SiteContent } from "./schema"

export const en: SiteContent = {
  locale: "en",
  meta: {
    title: "Stellara | AI Automation & Custom Software",
    description:
      "Stellara designs AI agents, connected workflows, and custom software that help businesses respond faster, operate more clearly, and convert more opportunities.",
    ogTitle: "Stellara — We automate the work behind your business.",
    ogDescription:
      "AI agents, connected workflows, and custom software, crafted in New York's Hudson Valley. No hype. Just outcomes.",
  },
  nav: [
    { id: "automate", label: "Where we work", href: "#work" },
    { id: "software", label: "Custom software", href: "#software" },
    { id: "process", label: "How it works", href: "#process" },
    { id: "about", label: "About", href: "#philosophy" },
  ],
  navCta: "Find your starting point",
  common: {
    skipToContent: "Skip to content",
    languageLabel: "Change language",
    languageEnglish: "English",
    languageSpanish: "Español",
    themeLabel: "Change theme",
    themeSystem: "System",
    themeLight: "Light",
    themeDark: "Dark",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    menuTitle: "Menu",
  },
  hero: {
    origin: "AI automation + custom software",
    headlinePrefix: "We automate the",
    headlineWord: "work",
    headlineSuffix: "behind your business.",
    rotatingWords: ["work", "calls", "leads", "follow-up", "scheduling", "support", "operations"],
    description:
      "Stellara designs AI agents, connected workflows, and custom software that help businesses respond faster, operate more clearly, and convert more of the opportunities they already create.",
    primaryCta: "Find your starting point",
    secondaryCta: "Explore what we automate",
    credibility: "AI automation and custom software built around how your business actually works.",
    observation: "Most businesses do not need more software. They need their existing work to move.",
    industryLabel: "See it in your business:",
    industryMore: "More",
    industryLess: "Less",
  },
  friction: {
    eyebrow: "Where business is lost",
    statements: [
      "A missed call becomes a missed job.",
      "A slow reply becomes a cold lead.",
      "A disconnected process becomes repeated work.",
      "An unclear handoff becomes a poor customer experience.",
    ],
    conclusion: "Stellara connects the moments where business is usually lost.",
  },
  work: {
    eyebrow: "Where we work",
    title: "Where Stellara goes to work.",
    description:
      "A piece of work enters your business. Stellara keeps it moving until a useful action happens — across the moments where work usually stalls.",
    pairs: [
      {
        id: "respond",
        index: "01",
        from: "Inquiry",
        to: "Response",
        headline: "Every inquiry gets answered.",
        description:
          "Phone, web, and messaging are answered the moment they arrive, intent is captured, and each request is routed to the right place.",
        capabilities: ["AI phone receptionist", "Website chat agent", "Missed-call recovery", "Speed-to-lead reply"],
      },
      {
        id: "answer",
        index: "02",
        from: "Call",
        to: "Conversation",
        headline: "Every call becomes a conversation.",
        description:
          "A voice agent answers day or night, understands what the caller needs, and books or routes them before the opportunity rings out.",
        capabilities: ["24/7 voice reception", "Intent capture", "Smart routing", "Live handoff"],
      },
      {
        id: "book",
        index: "03",
        from: "Lead",
        to: "Booked appointment",
        headline: "Interest turns into a booked appointment.",
        description:
          "Leads are qualified consistently, offered real availability, confirmed, and reminded — without the back-and-forth.",
        capabilities: ["Lead qualification", "Appointment setting", "Confirmations & reminders", "No-show recovery"],
      },
      {
        id: "followup",
        index: "04",
        from: "Quote",
        to: "Follow-up",
        headline: "Open quotes keep moving.",
        description:
          "Estimates and warm leads are followed up on a sensible cadence, and dormant relationships are reactivated instead of forgotten.",
        capabilities: ["Estimate follow-up", "Email & SMS nurture", "Pipeline movement", "Database reactivation"],
      },
      {
        id: "support",
        index: "05",
        from: "Question",
        to: "Resolved",
        headline: "Routine questions resolve themselves.",
        description:
          "An agent working from approved knowledge answers common questions, keeps customers informed, and asks for a review at the right moment.",
        capabilities: ["AI customer support", "Approved knowledge base", "Status updates", "Review requests"],
      },
      {
        id: "operate",
        index: "06",
        from: "Work",
        to: "Moved",
        headline: "Work moves without moving data by hand.",
        description:
          "The repetitive steps between the systems you already use are connected and automated, with clean visibility into what happened.",
        capabilities: ["Workflow orchestration", "Systems integration", "Data synchronization", "Operational reporting"],
      },
    ],
    boundariesTitle: "Every automation operates within clear boundaries",
    boundaries: [
      "Approved knowledge and instructions",
      "Human escalation",
      "Logged activity",
      "Connected workflows",
      "Measurable operational purpose",
    ],
  },
  explorer: {
    eyebrow: "Guided",
    title: "Find your starting point",
    intro:
      "Answer four short questions and we'll suggest a sensible first automation. This is a starting point, not a full consultation.",
    start: "Begin",
    progressLabel: "Question",
    q1: {
      prompt: "Where does work tend to slow down?",
      options: [
        { id: "inquiries", label: "New inquiries and missed calls" },
        { id: "followup", label: "Lead follow-up" },
        { id: "scheduling", label: "Scheduling" },
        { id: "support", label: "Customer support" },
        { id: "admin", label: "Internal administration" },
        { id: "systems", label: "Disconnected systems" },
        { id: "unsure", label: "I'm not sure yet" },
      ],
    },
    q2: {
      prompt: "What happens today?",
      options: [
        { id: "manual", label: "A person handles it manually" },
        { id: "spread", label: "It is spread across several tools" },
        { id: "lost", label: "We lose track of it" },
        { id: "available", label: "Response depends on who is available" },
        { id: "inconsistent", label: "We have a process, but it is inconsistent" },
      ],
    },
    q3: {
      prompt: "What matters most?",
      options: [
        { id: "faster", label: "Faster response" },
        { id: "booked", label: "More booked appointments" },
        { id: "fewer", label: "Fewer repetitive tasks" },
        { id: "experience", label: "Better customer experience" },
        { id: "visibility", label: "Cleaner operational visibility" },
        { id: "custom", label: "A system built around our workflow" },
      ],
    },
    q4: {
      prompt: "How does most of that work arrive?",
      options: [
        { id: "phone", label: "By phone" },
        { id: "web", label: "Web forms or chat" },
        { id: "email", label: "Email" },
        { id: "messaging", label: "Text or messaging" },
        { id: "referral", label: "Referrals and repeat clients" },
        { id: "mixed", label: "A mix of channels" },
      ],
    },
    back: "Back",
    resultEyebrow: "Recommended starting point",
    whyLabel: "Why it fits",
    componentsLabel: "Likely components",
    frictionLabel: "Current friction",
    systemLabel: "Stellara system",
    outcomeLabel: "Designed outcome",
    workflowLabel: "How the work moves",
    disclaimer: "A final recommendation always requires a short discovery conversation about your specific workflow.",
    resultCta: "Discuss this starting point",
    reset: "Start over",
    recommendations: [
      {
        id: "reception",
        title: "AI Reception & Lead Capture",
        why: "When inquiries and calls slip through, the first priority is making sure every opportunity is answered, understood, and routed.",
        components: ["AI phone receptionist", "Website conversational agent", "Missed-call recovery"],
        friction: "Calls and inquiries arrive faster than anyone can answer them, so opportunities ring out.",
        system: "An AI receptionist and web agent answer instantly, capture intent, and route every request.",
        outcome: "Every inquiry is answered, understood, and sent to the right place.",
        workflow: ["Incoming call", "Instant response", "Intent captured", "Routed", "Logged"],
      },
      {
        id: "speed",
        title: "Speed-to-Lead & Follow-Up",
        why: "When interest arrives but response is slow or uneven, consistent speed and structured follow-up recover opportunities you already earned.",
        components: ["Speed-to-lead response", "Lead qualification", "Email and SMS follow-up"],
        friction: "Interest arrives, but the first reply is slow or uneven, so warm leads go cold.",
        system: "Speed-to-lead replies respond in seconds and structured follow-up keeps the conversation moving.",
        outcome: "Leads you already earned get a fast, consistent response every time.",
        workflow: ["New lead", "Reply in seconds", "Qualified", "Follow-up", "Booked"],
      },
      {
        id: "appointment",
        title: "Appointment Coordination",
        why: "When scheduling depends on back-and-forth, automated coordination books more of the meetings you're already trying to set.",
        components: ["Appointment setting", "Confirmations and reminders", "No-show recovery"],
        friction: "Scheduling depends on back-and-forth, so meetings you almost set never happen.",
        system: "Automated coordination offers real availability, confirms, and reminds.",
        outcome: "More of the appointments you're already trying to set actually get booked.",
        workflow: ["Request", "Times offered", "Confirmed", "Reminder", "Attended"],
      },
      {
        id: "support",
        title: "AI Customer Support",
        why: "When routine questions consume your team, an agent working from approved knowledge handles the common ones and escalates the rest.",
        components: ["AI customer support", "Approved knowledge base", "Human escalation"],
        friction: "Routine questions pile onto your team and slow the real work.",
        system: "An agent on approved knowledge answers common questions and escalates the rest.",
        outcome: "Customers get fast answers while your team keeps its focus.",
        workflow: ["Question", "Understood", "Answered", "Escalated if needed", "Resolved"],
      },
      {
        id: "workflow",
        title: "Workflow Automation",
        why: "When repetitive administration slows delivery, automating the steps between systems removes friction without adding a new platform to manage.",
        components: ["Workflow orchestration", "Internal notifications", "Operational reporting"],
        friction: "Repetitive steps between systems slow down every delivery.",
        system: "Workflow automation moves the work and notifies the right people.",
        outcome: "Work moves between systems without anyone copying data by hand.",
        workflow: ["Trigger", "Data moved", "Team notified", "Updated", "Reported"],
      },
      {
        id: "integration",
        title: "Systems Integration",
        why: "When tools don't talk to each other, connecting them stops the manual copying that creates delay and error.",
        components: ["Systems integration", "Data synchronization", "APIs"],
        friction: "Your tools don't talk, so people copy the same data by hand.",
        system: "Integrations connect your systems and keep them in sync.",
        outcome: "One change updates everywhere, with no manual re-entry.",
        workflow: ["Event", "Synced", "Mapped", "Updated", "Verified"],
      },
      {
        id: "software",
        title: "Custom Software Discovery",
        why: "When no existing tool fits how you work, a focused discovery defines whether purpose-built software is the right investment.",
        components: ["Discovery workshop", "Process mapping", "Application scope"],
        friction: "No existing tool matches how you actually work.",
        system: "A focused discovery defines whether purpose-built software is the right investment.",
        outcome: "A clear scope for software shaped around your process.",
        workflow: ["Discovery", "Process mapped", "Scope defined", "Prototype", "Build plan"],
      },
    ],
    routing: {
      inquiries: "reception",
      followup: "speed",
      scheduling: "appointment",
      support: "support",
      admin: "workflow",
      systems: "integration",
      unsure: "software",
    },
  },
  process: {
    eyebrow: "How Stellara works",
    title: "A small, deliberate system before a large one.",
    phases: [
      {
        index: "01",
        title: "Observe",
        description:
          "We begin with the work itself: where requests arrive, how decisions are made, which systems are involved, and where momentum is lost.",
      },
      {
        index: "02",
        title: "Design",
        description: "We define the smallest useful system, its boundaries, its handoffs, and the outcome it should improve.",
      },
      {
        index: "03",
        title: "Build",
        description: "We configure agents, connect workflows, or develop custom software around the approved process.",
      },
      {
        index: "04",
        title: "Improve",
        description:
          "We review performance, refine the system, and expand only where additional automation makes practical sense.",
      },
    ],
  },
  software: {
    eyebrow: "Custom software",
    headline: "When the right tool doesn't exist, we build it.",
    description:
      "Some problems can be solved by connecting the systems you already use. Others require software shaped around your process. Stellara designs and develops focused business applications that turn operational knowledge into durable infrastructure.",
    capabilities: [
      "Internal business applications",
      "Customer and employee portals",
      "Workflow and approval systems",
      "Integrations and APIs",
      "Reporting and data applications",
      "AI-enabled tools",
      "Legacy process modernization",
    ],
    secondary: "Automation connects the work. Custom software can redefine it.",
    cta: "Discuss a software project",
  },
  industries: {
    eyebrow: "Industry applications",
    title: "Different businesses. Familiar points of friction.",
    description:
      "A missed inquiry, a delayed handoff, a repetitive process, and disconnected systems create the same kind of drag across very different industries. We begin with the workflow, then adapt the technology to the environment around it.",
    industries: [
      {
        id: "home",
        name: "Home & commercial services",
        examples: ["Missed-call response", "Estimate scheduling", "Lead follow-up", "Review requests"],
        flow: ["Incoming call", "Qualify", "Book", "Confirm", "Follow up"],
      },
      {
        id: "professional",
        name: "Professional services",
        examples: ["Inquiry qualification", "Consultation scheduling", "Intake workflows", "Document follow-up"],
        flow: ["New inquiry", "Qualify", "Schedule", "Collect info", "Follow up"],
      },
      {
        id: "healthcare",
        name: "Healthcare & wellness",
        examples: ["Inquiry response", "Appointment coordination", "Approved FAQ support", "Referral workflows"],
        flow: ["Patient inquiry", "Answer", "Schedule", "Remind", "Follow up"],
      },
      {
        id: "legal",
        name: "Legal & insurance",
        examples: ["New-matter intake", "Qualification and routing", "Status communication", "Document reminders"],
        flow: ["New inquiry", "Intake", "Qualify", "Route", "Schedule"],
      },
      {
        id: "property",
        name: "Property & real estate",
        examples: ["Inquiry routing", "Showing scheduling", "Resident communication", "Maintenance workflows"],
        flow: ["New lead", "Respond", "Qualify", "Route", "Schedule"],
      },
      {
        id: "ecommerce",
        name: "Ecommerce & customer operations",
        examples: ["Product and order questions", "Customer support", "Retention workflows", "Reactivation"],
        flow: ["Customer question", "Understand", "Resolve or route", "Update", "Follow up"],
      },
      {
        id: "government",
        name: "Local government",
        examples: ["Licensing and permitting intake", "Request routing", "Status communication", "Workflow coordination"],
        flow: ["Application", "Validate", "Route", "Review", "Notify"],
      },
      {
        id: "other",
        name: "Other operational businesses",
        examples: ["Inquiry capture", "Process automation", "Systems integration", "Custom applications"],
        flow: ["Request in", "Capture", "Route", "Automate", "Done"],
      },
    ],
    note: "Any solution involving regulated or sensitive information requires an appropriate discovery, security, privacy, and compliance review.",
    demoLabel: "Illustrative",
  },
  principles: {
    eyebrow: "Philosophy",
    title: "No hype. Just outcomes.",
    description:
      "AI is useful when it improves something that matters: response time, conversion, consistency, visibility, customer experience, or the amount of repetitive work your team carries. We begin there.",
    principles: [
      {
        title: "Start with the bottleneck",
        description: "Technology should solve a defined point of friction, not create another platform to manage.",
      },
      {
        title: "Keep people in control",
        description: "Automation should know its boundaries, escalate intelligently, and make the next human action clearer.",
      },
      {
        title: "Measure what changed",
        description: "We define useful signals before expanding the system.",
      },
    ],
  },
  appointment: {
    title: "Let's find the right starting point.",
    reassurance:
      "No generic AI pitch. We'll discuss the work, the bottleneck, and whether automation or custom software is a sensible fit.",
    step: "Step",
    of: "of",
    steps: { reason: "Reason", contact: "Contact", time: "Time", confirm: "Confirm" },
    reasonOptions: [
      { id: "agents", label: "AI agents" },
      { id: "workflow", label: "Workflow automation" },
      { id: "software", label: "Custom software" },
      { id: "integration", label: "Systems integration" },
      { id: "unsure", label: "Not sure yet" },
    ],
    fields: {
      name: "Name",
      email: "Work email",
      company: "Company",
      phone: "Phone",
      website: "Website",
      language: "Preferred language",
      description: "Short description of the operational problem",
      optional: "optional",
    },
    placeholders: {
      name: "Your name",
      email: "you@company.com",
      company: "Company name",
      phone: "(000) 000-0000",
      website: "https://",
      description: "What tends to slow down, and what you'd like to improve.",
    },
    timeIntro: "Choose a time that works for a short introductory call.",
    timeNote: "Times are illustrative and shown in your local time zone. We'll confirm the exact slot by email.",
    pickDay: "Select a day",
    pickTime: "Select a time",
    consent: "By submitting, you agree that Stellara may contact you about your inquiry. See our",
    privacyLink: "Privacy Policy",
    next: "Continue",
    back: "Back",
    submit: "Request this time",
    submitting: "Sending…",
    confirmTitle: "Request received",
    confirmReason: "Reason",
    confirmTime: "Requested time",
    confirmEmail: "Contact email",
    whatNext: "What to expect next",
    whatNextBody:
      "We'll confirm your time by email and share a short agenda focused on the work you described. No preparation required.",
    close: "Close",
    errors: {
      name: "Please enter your name.",
      email: "Please enter your work email.",
      emailInvalid: "Please enter a valid email address.",
      company: "Please enter your company.",
      reason: "Please choose a reason for the conversation.",
      time: "Please select a day and time.",
      consent: "Please accept the contact consent to continue.",
    },
  },
  assistant: {
    launcherLabel: "Open Stellara assistant",
    title: "Stellara assistant",
    status: "Explore what could be automated",
    intro:
      "Hi. I can help you explore where automation or custom software may be useful. Where does work tend to slow down?",
    quickReplies: [
      { id: "inquiries", label: "Missed calls" },
      { id: "followup", label: "Lead follow-up" },
      { id: "scheduling", label: "Scheduling" },
      { id: "support", label: "Customer support" },
      { id: "admin", label: "Repetitive admin" },
      { id: "systems", label: "Disconnected systems" },
      { id: "unsure", label: "Something else" },
    ],
    followUp: "Got it. And what matters most as an outcome?",
    recommendPrefix: "Based on that, a sensible starting point is",
    whyPrefix: "Why:",
    bookCta: "Open the appointment flow",
    restart: "Start over",
    restartLabel: "Restart conversation",
    minimizeLabel: "Minimize assistant",
    closeLabel: "Close assistant",
    disclaimer: "This is an interactive guide, not a human agent, and it can't access private company data.",
    inputPlaceholder: "Type a message…",
    send: "Send",
    guideNote: "Guided demonstration",
  },
  finalCta: {
    headline: "Start with the work that should move better.",
    description:
      "You do not need an AI roadmap before the first conversation. Bring us the process that is slow, inconsistent, repetitive, or too dependent on manual follow-up.",
    primaryCta: "Find your starting point",
    secondaryCta: "Talk with Stellara",
  },
  footer: {
    descriptor: "AI automation and custom software for the work behind your business.",
    navTitle: "Explore",
    contactTitle: "Contact",
    contactPlaceholder: "Start a conversation",
    legalTitle: "Legal",
    privacy: "Privacy",
    terms: "Terms",
    crafted: "Crafted in the Hudson Valley.",
    rights: "All rights reserved.",
  },
  whatsapp: {
    label: "Contact Stellara on WhatsApp",
    message: "Hola, me interesa conocer cómo Stellara podría ayudar a automatizar un proceso en mi empresa.",
    cta: "WhatsApp",
  },
  privacy: {
    title: "Privacy Policy",
    updated: "Last updated",
    reviewNote: "This is a template shell. Fields marked for review require business-specific legal review before publication.",
    intro:
      "This policy explains, in plain language, how Stellara handles information shared through this website. It is a starting template and should be reviewed by qualified counsel before it is relied upon.",
    sections: [
      {
        heading: "Information we collect",
        body: [
          "We collect the information you choose to provide through our contact and appointment forms, such as your name, work email, company, and a description of your operational problem.",
          "We may collect limited technical information (such as general analytics events) that does not include personally identifiable information.",
        ],
      },
      {
        heading: "How we use information",
        body: [
          "We use the information you provide to respond to your inquiry, prepare for a conversation, and follow up about the work you described.",
          "We do not sell your information. [Review: confirm data-handling commitments with counsel.]",
        ],
      },
      {
        heading: "Data retention",
        body: ["[Review: define retention periods appropriate to your jurisdiction and business.]"],
      },
      {
        heading: "Your choices",
        body: ["You may request access to or deletion of the information you shared by contacting us. [Review: confirm applicable rights.]"],
      },
      {
        heading: "Contact",
        body: ["Questions about this policy can be directed to the contact channel listed on this site."],
      },
    ],
    backHome: "Back to home",
  },
  terms: {
    title: "Terms of Service",
    updated: "Last updated",
    reviewNote: "This is a template shell. Fields marked for review require business-specific legal review before publication.",
    intro:
      "These terms describe, in plain language, the basis on which this website is provided. They are a starting template and should be reviewed by qualified counsel before they are relied upon.",
    sections: [
      {
        heading: "Use of this website",
        body: [
          "This website is provided for general information about Stellara's services. Content may change without notice.",
          "Nothing on this website constitutes a binding offer, warranty, or guarantee of specific results.",
        ],
      },
      {
        heading: "Inquiries and appointments",
        body: [
          "Submitting a form or requesting an appointment begins a conversation and does not create a contract for services.",
          "[Review: add engagement, scope, and payment terms with counsel.]",
        ],
      },
      {
        heading: "Intellectual property",
        body: ["The Stellara name, wordmark, and brand materials remain the property of Stellara. [Review: confirm with counsel.]"],
      },
      {
        heading: "Limitation of liability",
        body: ["[Review: add jurisdiction-appropriate limitation of liability language with counsel.]"],
      },
      {
        heading: "Contact",
        body: ["Questions about these terms can be directed to the contact channel listed on this site."],
      },
    ],
    backHome: "Back to home",
  },
}
