import type { SiteContent } from "./schema"

export const en: SiteContent = {
  locale: "en",
  meta: {
    title: "Stellara | AI Automation & Custom Software",
    description:
      "Stellara designs AI agents, connected workflows, and custom software that help businesses respond faster, operate more clearly, and convert more opportunities.",
    ogTitle: "Stellara — We automate the work behind your business.",
    ogDescription:
      "AI agents, connected workflows, and custom software, crafted in New York's Hudson Valley. No hype. Just outcomes.",
  },
  nav: [
    { id: "demo", label: "Demo", href: "#personalized-demo" },
    { id: "fit", label: "How it fits", href: "#fit" },
    { id: "plans", label: "Plans", href: "#plans" },
    { id: "faq", label: "FAQ", href: "#faq" },
  ],
  navCta: "Build My Firm's Demo",
  common: {
    skipToContent: "Skip to content",
    languageLabel: "Change language",
    languageEnglish: "English",
    languageSpanish: "Español",
    themeLabel: "Change theme",
    themeSystem: "System",
    themeLight: "Light",
    themeDark: "Dark",
    openMenu: "Open menu",
    closeMenu: "Close menu",
  },
  hero: {
    headline: "Automation built for PIP firms.",
    supporting: "Capture more opportunities. Keep clients moving. Take repetitive work off your team.",
    selectorQuestion: "See how Stellara does it.",
    services: [
      { id: "after-hours", label: "24/7 Intake" },
      { id: "treatment-follow-up", label: "Treatment Follow-Up" },
      { id: "website-intake", label: "Website Intake" },
      { id: "reviews", label: "Reviews" }
    ],
  },
  personalizedDemo: {
    eyebrow: "Personalized demo",
    title: "Now see it work for your firm.",
    description:
      "Enter your firm's website. We'll create a personalized Stellara intake demo so you can experience what your prospective clients would experience.",
    fields: {
      websiteLabel: "Law firm website",
      websitePlaceholder: "https://yourfirm.com",
      firstNameLabel: "First name",
      firstNamePlaceholder: "Jane",
      lastNameLabel: "Last name",
      lastNamePlaceholder: "Doe",
      mobileLabel: "Mobile number",
      mobilePlaceholder: "(000) 000-0000",
      emailLabel: "Email",
      emailPlaceholder: "you@firm.com",
    },
    cta: "Build My Firm's Demo",
    secondaryCta: "Talk to Us",
    helperText: "UI preview only. Backend demo delivery is connected in the next implementation phase.",
    submittedText: "Demo request capture is currently UI only. Form submission logic will be connected next.",
    steps: [
      {
        index: "01",
        title: "Enter your website",
        body: "We personalize the experience around your firm.",
      },
      {
        index: "02",
        title: "Get your demo",
        body: "We'll text you a private demo link and test phone number.",
      },
      {
        index: "03",
        title: "Become the client",
        body: "Call your AI intake assistant, test the experience, and see what your staff would receive.",
      },
    ],
  },
  howItFits: {
    eyebrow: "How it fits",
    title: "Works around your team. Not instead of it.",
    description:
      "Stellara handles repetitive steps between incoming client activity and the systems and staff your firm already uses.",
    takeaway: "Routine steps keep moving. Your team stays informed and in control.",
    illustrative: "Illustrative workflow · fictional data",
    scenarioLabel: "Choose a workflow",
    replay: "Replay",
    replayLabel: "Replay this workflow",
    ownerLabels: {
      auto: "Handled automatically",
      handoff: "Staff action needed",
      staff: "Your team decides",
    },
    nextLabel: "Next action",
    scenarios: [
      {
        id: "new-inquiry",
        label: "New inquiry",
        steps: [
          {
            stage: "An inquiry arrives",
            owner: "auto",
            title: "Daniel Ortiz",
            meta: "Web form · 7:48 PM",
            lines: ["\u201CI was rear-ended last week and I\u2019m seeing a chiropractor.\u201D"],
          },
          {
            stage: "Stellara handles the next step",
            owner: "auto",
            title: "Basic details collected",
            meta: "7:49 PM",
            lines: ["Accident date: Sep 24", "Currently treating: Yes", "Prefers a call after 9 AM"],
          },
          {
            stage: "Your team gets the context",
            owner: "handoff",
            title: "Intake team notified",
            meta: "7:50 PM",
            lines: ["Rear-end collision, treating with a chiropractor", "No current attorney reported"],
            next: "Review and respond",
          },
          {
            stage: "Your staff takes over",
            owner: "staff",
            title: "Ana reviews the inquiry",
            meta: "8:15 AM",
            lines: ["Calls Daniel to discuss next steps"],
          },
        ],
      },
      {
        id: "treatment-follow-up",
        label: "Treatment follow-up",
        steps: [
          {
            stage: "A check-in goes out",
            owner: "auto",
            title: "Maria Santos",
            meta: "Scheduled text · Thu 10:00 AM",
            lines: ["\u201CHi Maria, checking in on your treatment. How are things going?\u201D"],
          },
          {
            stage: "A reply comes back",
            owner: "auto",
            title: "Missed appointment mentioned",
            meta: "Thu 10:12 AM",
            lines: ["\u201CI missed PT on Tuesday. Car trouble.\u201D"],
          },
          {
            stage: "Your team gets the context",
            owner: "handoff",
            title: "Flagged for staff follow-up",
            meta: "Thu 10:12 AM",
            lines: ["Missed physical therapy on Tuesday", "Reason given: transportation"],
            next: "Call to help reschedule",
          },
          {
            stage: "Your staff takes over",
            owner: "staff",
            title: "Ana calls Maria",
            meta: "Thu 10:40 AM",
            lines: ["Helps her get back on her treatment schedule"],
          },
        ],
      },
      {
        id: "review-request",
        label: "Review request",
        steps: [
          {
            stage: "A milestone is reached",
            owner: "auto",
            title: "James Carter",
            meta: "Matter closed · Mon 2:10 PM",
            lines: ["Firm rule: request a review when a matter closes"],
          },
          {
            stage: "Stellara sends the request",
            owner: "auto",
            title: "Neutral review request sent",
            meta: "Mon 2:11 PM",
            lines: ["Same request for every client at this milestone", "One reminder if there\u2019s no response"],
          },
          {
            stage: "Your team gets the context",
            owner: "handoff",
            title: "Reply needs attention",
            meta: "Tue 9:05 AM",
            lines: ["\u201CCan someone call me about my final paperwork?\u201D"],
            next: "Respond personally",
          },
          {
            stage: "Your staff takes over",
            owner: "staff",
            title: "Ana responds",
            meta: "Tue 9:30 AM",
            lines: ["Calls James about his paperwork"],
          },
        ],
      },
    ],
    footnote:
      "Your team steps in where people are needed. Stellara handles the repetitive work around them.",
  },
  measurableWork: {
    eyebrow: "Visibility",
    title: "See what's getting done.",
    description:
      "Know what's being handled, what needs attention, and where opportunities may be falling through the cracks.",
    reportLabel: "Example reporting",
    dashboardLabel: "Illustrative dashboard",
    periodLabel: "Last 30 days",
    attentionLabel: "Needs your team",
    attention: [
      { label: "Missed PT appointment reported", meta: "Maria S. · Treatment follow-up", status: "Staff action needed", tone: "handoff" },
      { label: "Consultation requested", meta: "Daniel O. · Website", status: "Staff action needed", tone: "handoff" },
      { label: "Review request reminder sent", meta: "James C. · Reviews", status: "Handled automatically", tone: "auto" },
    ],
    metrics: [
      { label: "Inquiries handled", value: "146" },
      { label: "Response time", value: "00:42" },
      { label: "Qualified inquiries", value: "58" },
      { label: "Consultations booked", value: "31" },
      { label: "Follow-ups completed", value: "82" },
      { label: "Treatment follow-ups", value: "37" },
      { label: "Reviews requested", value: "49" },
    ],
  },
  stories: {
    controls: {
      previous: "Previous scene",
      next: "Next scene",
      progress: "Scene {current} of {total}",
      illustrative: "Illustrative example · fictional data",
      handledAutomatically: "Handled automatically",
      staffActionNeeded: "Staff action needed",
      intakeAriaLabel: "24/7 intake: how Stellara handles inquiries when your office is closed",
    },
    treatment: {
      ariaLabel: "Treatment follow-up: how Stellara checks in with clients and flags what needs your team",
      scenes: [
        {
          time: "Thu 10:00 AM",
          step: "Scheduled",
          title: "Check-in scheduled",
          headline: "Check-ins go out on schedule.",
          body: "Set the cadence once. Every client gets a timely, consistent touchpoint.",
          summary: "A treatment check-in for Maria Santos is scheduled for Thursday at 10 AM alongside other clients.",
        },
        {
          time: "Thu 10:00 AM",
          step: "Delivered",
          title: "Message delivered",
          headline: "A friendly message, sent for you.",
          body: "Written in your firm\u2019s voice and delivered by text.",
          summary: "The check-in text is delivered to Maria asking how her treatment is going.",
        },
        {
          time: "Thu 10:12 AM",
          step: "Reply",
          title: "Client replies",
          headline: "Maria mentions a missed appointment.",
          body: "Replies are read for details your team would want to know.",
          summary: "Maria replies that she missed her physical therapy appointment on Tuesday because of car trouble.",
        },
        {
          time: "Thu 10:12 AM",
          step: "Alert",
          title: "Staff alerted",
          headline: "Your team gets the full context.",
          headlineAccent: "Instantly.",
          body: "A concise alert with what happened and a suggested next step.",
          summary: "Staff receive an alert summarizing the missed appointment and a suggested next step to call and help reschedule.",
        },
        {
          time: "Thu 10:40 AM",
          step: "Follow-up",
          title: "Staff follows up",
          headline: "Your staff takes it from here.",
          body: "The relationship and every judgment call stay with your firm.",
          summary: "A team member calls Maria and helps her get back on her treatment schedule.",
        },
      ],
      ui: {
        queueTitle: "Check-in schedule",
        checkinType: "Treatment check-in",
        statusScheduled: "Scheduled",
        queue: [
          { name: "Maria Santos", when: "Thu 10:00 AM" },
          { name: "Kevin Brooks", when: "Thu 11:30 AM" },
          { name: "Lucia Mendez", when: "Fri 9:00 AM" },
        ],
        smsFrom: "Linden Law · Text",
        outgoing: "Hi Maria, it\u2019s Linden Law checking in. How is your treatment going? Reply anytime.",
        delivered: "Delivered",
        reply: "Honestly not great. I missed PT on Tuesday, car trouble.",
        replyTime: "10:12 AM",
        flag: "Mentions a missed appointment",
        alertTitle: "Follow-up flagged",
        alertClient: "Maria Santos · PIP matter",
        alertDetails: ["Missed physical therapy on Tuesday", "Reason given: transportation", "No new visit scheduled"],
        alertNext: "Call to help reschedule",
        assignee: "Ana · Intake team",
        takeoverTitle: "Staff follow-up",
        takeoverLines: ["Called Maria at 10:40 AM", "Helped reschedule with her provider"],
        takeoverNote: "Your team decides what happens next.",
      },
    },
    reviews: {
      ariaLabel: "Reviews: how Stellara sends consistent review requests after a firm-defined milestone",
      scenes: [
        {
          time: "Mon 2:10 PM",
          step: "Milestone",
          title: "Milestone reached",
          headline: "You choose the moment.",
          body: "Requests follow a milestone your firm defines, for every client who reaches it.",
          summary: "James Carter's matter is marked closed, which matches the firm's review request rule.",
        },
        {
          time: "Mon 2:11 PM",
          step: "Request",
          title: "Neutral request sent",
          headline: "A neutral, respectful request.",
          body: "The same wording for every client. No pressure, no filtering.",
          summary: "A neutral text thanks James and invites him to share his experience if he is willing.",
        },
        {
          time: "Mon 6:30 PM",
          step: "Link",
          title: "Easy review link",
          headline: "One tap to share feedback.",
          body: "A simple page that points to your review profile.",
          summary: "James opens a simple page with a link to write a review and a way to contact the firm directly.",
        },
        {
          time: "Thu 2:10 PM",
          step: "Reminder",
          title: "Gentle reminder",
          headline: "One reminder, then it stops.",
          body: "Reminder rules are set by your firm, and opt-outs are always respected.",
          summary: "If there's no response, a single reminder is sent three days later. It stops if the client opts out.",
        },
        {
          time: "Fri 9:00 AM",
          step: "Activity",
          title: "Activity visible",
          headline: "Every request, in one view.",
          headlineAccent: "Nothing guessed.",
          body: "See what was sent and which replies need a person.",
          summary: "The firm sees each request's status, including a reply that needs staff attention.",
        },
      ],
      ui: {
        ruleTitle: "Review request rule",
        ruleWhen: "When",
        ruleTrigger: "Matter marked closed",
        ruleThen: "Then",
        ruleAction: "Send review request",
        ruleNote: "Applies to every client at this milestone",
        milestoneEvent: "James Carter · Matter closed",
        smsFrom: "Linden Law · Text",
        request:
          "Hi James, thank you for trusting Linden Law. If you\u2019re willing, we\u2019d appreciate you sharing your experience.",
        delivered: "Delivered",
        linkTitle: "Share your experience",
        linkBody: "Your feedback helps other people find the right firm.",
        linkCta: "Write a review",
        linkContact: "Questions? Contact the firm directly",
        reminderTitle: "Reminder",
        reminderWhen: "3 days later",
        reminder: "Hi James, just a friendly reminder in case you\u2019d like to share your experience. Thank you!",
        reminderRules: ["One reminder at most", "Stops if the client opts out"],
        activityTitle: "Review requests",
        activity: [
          { name: "James Carter", status: "Reminder sent", tone: "auto" },
          { name: "Rosa Diaz", status: "Link opened", tone: "auto" },
          { name: "Tom Nguyen", status: "Reply needs attention", tone: "handoff" },
          { name: "Grace Kim", status: "Completed", tone: "done" },
        ],
      },
    },
    website: {
      ariaLabel: "Smart website: how Stellara helps an interested visitor request a consultation",
      scenes: [
        {
          time: "9:42 PM",
          step: "Visitor",
          title: "Visitor arrives",
          headline: "A visitor lands on your site.",
          body: "After hours, from a search for PIP help.",
          summary: "A visitor arrives on the firm's PIP claims page at 9:42 PM.",
        },
        {
          time: "9:43 PM",
          step: "Question",
          title: "Asks a question",
          headline: "Questions get a helpful reply.",
          body: "General information, never legal advice, and a clear next step.",
          summary: "The visitor asks whether PIP covers physical therapy. The assistant explains an attorney can review it and offers to help request a consultation.",
        },
        {
          time: "9:44 PM",
          step: "Details",
          title: "Shares details",
          headline: "Basic details, collected naturally.",
          body: "Just enough for your team to follow up well.",
          summary: "The visitor shares their name, accident date, treatment status and best phone number.",
        },
        {
          time: "9:45 PM",
          step: "Consultation",
          title: "Requests a consultation",
          headline: "The next step is one tap away.",
          body: "Visitors pick a time. Your team confirms it.",
          summary: "The visitor requests a consultation for Thursday at 11 AM, pending confirmation by the firm.",
        },
        {
          time: "8:00 AM",
          step: "Summary",
          title: "Staff gets a summary",
          headline: "Your team starts with the full picture.",
          headlineAccent: "Not a blank form.",
          body: "A concise summary and a clear next action.",
          summary: "Staff receive a summary of the website inquiry and a next step to confirm the consultation.",
        },
      ],
      ui: {
        url: "lindenlaw.com/pip-claims",
        siteHeadline: "Hurt in a car accident?",
        siteBody: "Learn how PIP coverage works and talk to our team.",
        siteCta: "Free consultation",
        visitor: "New visitor · 9:42 PM",
        chatPrompt: "Questions? Chat with us",
        chatTitle: "Linden Law assistant",
        question: "Does PIP cover my physical therapy?",
        answer:
          "Coverage depends on your situation, and an attorney can review it with you. I can take a few details and help you request a consultation.",
        infoNote: "General information only. Not legal advice.",
        detailsTitle: "Inquiry details",
        details: [
          { label: "Name", value: "Daniel Ortiz" },
          { label: "Accident date", value: "Sep 24" },
          { label: "Currently treating", value: "Yes" },
          { label: "Best phone", value: "(845) 555-0142" },
        ],
        consultTitle: "Request a consultation",
        slots: ["Thu 9:30 AM", "Thu 11:00 AM", "Fri 2:00 PM"],
        consultSent: "Request sent. The firm will confirm.",
        summaryTitle: "New website inquiry",
        summaryLines: ["Daniel Ortiz · rear-end collision Sep 24", "Treating with a chiropractor", "Requested Thu 11:00 AM"],
        summaryNext: "Confirm the consultation",
      },
    },
  },
  plans: {
    eyebrow: "Plans",
    title: "Start with the workflows that matter most.",
    description: "Two clear starting points for founders pricing. Choose the workflow depth your firm needs first.",
    badge: "Founders pricing · first 5 firms",
    monthlyPriceLabel: "Monthly price",
    implementationLabel: "One-time implementation",
    featureHeader: "Feature",
    essentialsLabel: "Essentials",
    proLabel: "Pro",
    recommendedLabel: "Recommended",
    perMonthLabel: "/mo",
    coreGroupLabel: "Included in both",
    proGroupLabel: "Pro adds",
    includedEssentialsAria: "Included in Essentials",
    notIncludedEssentialsAria: "Not included in Essentials",
    includedProAria: "Included in Pro",
    notIncludedProAria: "Not included in Pro",
    distinction:
      "The distinction: Essentials captures inquiries, books consultations, and requests reviews. Pro adds website intake and ongoing follow-up with prospects and clients.",
    addOnsLabel: "Optional add-ons (up to 3)",
    primaryCta: "See Stellara in Action",
    secondaryCta: "Talk to Us",
    plans: [
      {
        name: "Essentials",
        monthly: "$497",
        implementation: "$500",
        summary: "Captures inquiries, books consultations, and requests reviews.",
        points: [
          "AI call answering / after-hours intake",
          "Missed-call recovery / text-back",
          "Consultation booking and reminders",
          "Automated review requests",
          "Monthly results reporting",
        ],
      },
      {
        name: "Pro",
        highlighted: true,
        monthly: "$997",
        implementation: "$1,000",
        summary: "Adds website intake and ongoing follow-up with prospects and clients.",
        points: [
          "Everything in Essentials",
          "Website AI intake agent",
          "Prospective-client follow-up and re-engagement",
          "Treatment follow-up",
          "Lead/client pipeline visibility",
        ],
      },
    ],
    addOns: [
      "Smart Website Upgrade",
      "Unconverted Inquiry Reactivation",
      "Custom Intake & Case-System Integration",
    ],
    features: [
      { label: "AI call answering / after-hours intake", essentials: true, pro: true },
      { label: "Missed-call recovery / text-back", essentials: true, pro: true },
      { label: "Consultation booking and reminders", essentials: true, pro: true },
      { label: "Automated review requests", essentials: true, pro: true },
      { label: "Monthly results reporting", essentials: true, pro: true },
      { label: "Website AI intake agent", essentials: false, pro: true },
      { label: "Prospective-client follow-up and re-engagement", essentials: false, pro: true },
      { label: "Treatment follow-up", essentials: false, pro: true },
      { label: "Lead/client pipeline visibility", essentials: false, pro: true },
    ],
  },
  trustFounder: {
    eyebrow: "Trust",
    title: "Built differently on purpose.",
    description:
      "Specialized, hands-on, and intentionally focused on the workflows boutique PIP firms need to move every day.",
    imagePlaceholder: "Founder photograph placeholder",
    paragraphOne:
      "Stellara was built around a simple idea: firms should not need larger teams to deliver responsive, consistent client experiences.",
    paragraphTwo:
      "We combine software, automation and AI around the workflows your firm already uses, then measure whether the work is actually getting done.",
    tagline: "Boutique by design. Hands-on by default.",
  },
  faqFinalCta: {
    eyebrow: "FAQ",
    title: "Questions before you try it",
    description: "Clear, practical answers. Final implementation details are scoped with your firm before launch.",
    faqs: [
      {
        q: "Does Stellara replace our intake staff?",
        a: "No. Stellara is designed to handle repetitive workflow steps and hand off to your team where human judgment is needed.",
      },
      {
        q: "What happens when a conversation needs a human?",
        a: "Human handoff paths are configured during implementation. Final escalation rules are tailored with your team.",
      },
      {
        q: "Can we decide which inquiries meet our intake criteria?",
        a: "Yes. Intake criteria are firm-defined and reviewed during setup before workflows are finalized.",
      },
      {
        q: "Can Stellara handle Spanish?",
        a: "Spanish workflows can be configured as part of implementation. Exact language coverage is confirmed in your setup scope.",
      },
      {
        q: "Can Stellara work with our existing systems?",
        a: "Integration scope varies by firm. Existing systems are reviewed first, then feasible integration paths are mapped.",
      },
      {
        q: "How long does implementation take?",
        a: "Timeline depends on selected workflows and integration depth. A clear rollout plan is provided before work begins.",
      },
      {
        q: "What can we measure?",
        a: "You can measure operational workflow activity such as inquiries handled, follow-up completion, and booking outcomes. Exact reporting is defined with your team.",
      },
    ],
    finalTitle: "See Stellara working for your firm.",
    finalDescription: "Experience your own intake workflow before you ever have to talk to us.",
    primaryCta: "Build My Firm's Demo",
    secondaryCta: "Talk to Us",
  },
  explorer: {
    q3: {
      prompt: "What matters most?",
      options: [
        { id: "faster", label: "Faster response" },
        { id: "booked", label: "More booked appointments" },
        { id: "fewer", label: "Fewer repetitive tasks" },
        { id: "experience", label: "Better customer experience" },
        { id: "visibility", label: "Cleaner operational visibility" },
        { id: "custom", label: "A system built around our workflow" },
      ],
    },
    componentsLabel: "Likely components",
    recommendations: [
      {
        id: "reception",
        title: "AI Reception & Lead Capture",
        why: "When inquiries and calls slip through, the first priority is making sure every opportunity is answered, understood, and routed.",
        components: ["AI phone receptionist", "Website conversational agent", "Missed-call recovery"],
      },
      {
        id: "speed",
        title: "Speed-to-Lead & Follow-Up",
        why: "When interest arrives but response is slow or uneven, consistent speed and structured follow-up recover opportunities you already earned.",
        components: ["Speed-to-lead response", "Lead qualification", "Email and SMS follow-up"],
      },
      {
        id: "appointment",
        title: "Appointment Coordination",
        why: "When scheduling depends on back-and-forth, automated coordination books more of the meetings you're already trying to set.",
        components: ["Appointment setting", "Confirmations and reminders", "No-show recovery"],
      },
      {
        id: "support",
        title: "AI Customer Support",
        why: "When routine questions consume your team, an agent working from approved knowledge handles the common ones and escalates the rest.",
        components: ["AI customer support", "Approved knowledge base", "Human escalation"],
      },
      {
        id: "workflow",
        title: "Workflow Automation",
        why: "When repetitive administration slows delivery, automating the steps between systems removes friction without adding a new platform to manage.",
        components: ["Workflow orchestration", "Internal notifications", "Operational reporting"],
      },
      {
        id: "integration",
        title: "Systems Integration",
        why: "When tools don't talk to each other, connecting them stops the manual copying that creates delay and error.",
        components: ["Systems integration", "Data synchronization", "APIs"],
      },
      {
        id: "software",
        title: "Custom Software Discovery",
        why: "When no existing tool fits how you work, a focused discovery defines whether purpose-built software is the right investment.",
        components: ["Discovery workshop", "Process mapping", "Application scope"],
      },
    ],
    routing: {
      inquiries: "reception",
      followup: "speed",
      scheduling: "appointment",
      support: "support",
      admin: "workflow",
      systems: "integration",
      unsure: "software",
    },
  },
  appointment: {
    title: "Let's find the right starting point.",
    reassurance:
      "No generic AI pitch. We'll discuss the work, the bottleneck, and whether automation or custom software is a sensible fit.",
    step: "Step",
    of: "of",
    steps: { reason: "Reason", contact: "Contact", time: "Time", confirm: "Confirm" },
    reasonOptions: [
      { id: "agents", label: "AI agents" },
      { id: "workflow", label: "Workflow automation" },
      { id: "software", label: "Custom software" },
      { id: "integration", label: "Systems integration" },
      { id: "unsure", label: "Not sure yet" },
    ],
    fields: {
      name: "Name",
      email: "Work email",
      company: "Company",
      phone: "Phone",
      website: "Website",
      language: "Preferred language",
      description: "Short description of the operational problem",
      optional: "optional",
    },
    placeholders: {
      name: "Your name",
      email: "you@company.com",
      company: "Company name",
      phone: "(000) 000-0000",
      website: "https://",
      description: "What tends to slow down, and what you'd like to improve.",
    },
    timeIntro: "Choose a time that works for a short introductory call.",
    timeNote: "Times are illustrative and shown in your local time zone. We'll confirm the exact slot by email.",
    pickDay: "Select a day",
    pickTime: "Select a time",
    consent: "By submitting, you agree that Stellara may contact you about your inquiry. See our",
    privacyLink: "Privacy Policy",
    next: "Continue",
    back: "Back",
    submit: "Request this time",
    submitting: "Sending…",
    confirmTitle: "Request received",
    confirmReason: "Reason",
    confirmTime: "Requested time",
    confirmEmail: "Contact email",
    whatNext: "What to expect next",
    whatNextBody:
      "We'll confirm your time by email and share a short agenda focused on the work you described. No preparation required.",
    close: "Close",
    errors: {
      name: "Please enter your name.",
      email: "Please enter your work email.",
      emailInvalid: "Please enter a valid email address.",
      company: "Please enter your company.",
      reason: "Please choose a reason for the conversation.",
      time: "Please select a day and time.",
      consent: "Please accept the contact consent to continue.",
    },
  },
  assistant: {
    launcherLabel: "Open Stellara assistant",
    title: "Stellara assistant",
    intro:
      "Hi. I can help you explore where automation or custom software may be useful. Where does work tend to slow down?",
    quickReplies: [
      { id: "inquiries", label: "Missed calls" },
      { id: "followup", label: "Lead follow-up" },
      { id: "scheduling", label: "Scheduling" },
      { id: "support", label: "Customer support" },
      { id: "admin", label: "Repetitive admin" },
      { id: "systems", label: "Disconnected systems" },
      { id: "unsure", label: "Something else" },
    ],
    followUp: "Got it. And what matters most as an outcome?",
    recommendPrefix: "Based on that, a sensible starting point is",
    whyPrefix: "Why:",
    bookCta: "Open the appointment flow",
    restart: "Start over",
    restartLabel: "Restart conversation",
    closeLabel: "Close assistant",
    disclaimer: "This is an interactive guide, not a human agent, and it can't access private company data.",
    guideNote: "Guided demonstration",
  },
  footer: {
    descriptor: "AI automation and custom software for the work behind your business.",
    navTitle: "Explore",
    contactTitle: "Contact",
    contactPlaceholder: "Start a conversation",
    legalTitle: "Legal",
    privacy: "Privacy",
    terms: "Terms",
    crafted: "Crafted in the Hudson Valley.",
    rights: "All rights reserved.",
  },
  whatsapp: {
    label: "Contact Stellara on WhatsApp",
    message: "Hola, me interesa conocer cómo Stellara podría ayudar a automatizar un proceso en mi empresa.",
    cta: "WhatsApp",
  },
  privacy: {
    title: "Privacy Policy",
    updated: "Last updated",
    reviewNote: "This is a template shell. Fields marked for review require business-specific legal review before publication.",
    intro:
      "This policy explains, in plain language, how Stellara handles information shared through this website. It is a starting template and should be reviewed by qualified counsel before it is relied upon.",
    sections: [
      {
        heading: "Information we collect",
        body: [
          "We collect the information you choose to provide through our contact and appointment forms, such as your name, work email, company, and a description of your operational problem.",
          "We may collect limited technical information (such as general analytics events) that does not include personally identifiable information.",
        ],
      },
      {
        heading: "How we use information",
        body: [
          "We use the information you provide to respond to your inquiry, prepare for a conversation, and follow up about the work you described.",
          "We do not sell your information. [Review: confirm data-handling commitments with counsel.]",
        ],
      },
      {
        heading: "Data retention",
        body: ["[Review: define retention periods appropriate to your jurisdiction and business.]"],
      },
      {
        heading: "Your choices",
        body: ["You may request access to or deletion of the information you shared by contacting us. [Review: confirm applicable rights.]"],
      },
      {
        heading: "Contact",
        body: ["Questions about this policy can be directed to the contact channel listed on this site."],
      },
    ],
    backHome: "Back to home",
  },
  terms: {
    title: "Terms of Service",
    updated: "Last updated",
    reviewNote: "This is a template shell. Fields marked for review require business-specific legal review before publication.",
    intro:
      "These terms describe, in plain language, the basis on which this website is provided. They are a starting template and should be reviewed by qualified counsel before they are relied upon.",
    sections: [
      {
        heading: "Use of this website",
        body: [
          "This website is provided for general information about Stellara's services. Content may change without notice.",
          "Nothing on this website constitutes a binding offer, warranty, or guarantee of specific results.",
        ],
      },
      {
        heading: "Inquiries and appointments",
        body: [
          "Submitting a form or requesting an appointment begins a conversation and does not create a contract for services.",
          "[Review: add engagement, scope, and payment terms with counsel.]",
        ],
      },
      {
        heading: "Intellectual property",
        body: ["The Stellara name, wordmark, and brand materials remain the property of Stellara. [Review: confirm with counsel.]"],
      },
      {
        heading: "Limitation of liability",
        body: ["[Review: add jurisdiction-appropriate limitation of liability language with counsel.]"],
      },
      {
        heading: "Contact",
        body: ["Questions about these terms can be directed to the contact channel listed on this site."],
      },
    ],
    backHome: "Back to home",
  },
}
