import type { SiteContent } from "./schema"

export const es: SiteContent = {
  locale: "es",
  meta: {
    title: "Stellara | Automatización con IA y software a medida",
    description:
      "Stellara diseña agentes de IA, flujos conectados y software a medida para ayudar a las empresas a responder más rápido, operar con claridad y aprovechar más oportunidades.",
    ogTitle: "Stellara — Automatizamos el trabajo que mueve su negocio.",
    ogDescription:
      "Agentes de IA, flujos conectados y software a medida, creados en el Hudson Valley de Nueva York. Menos humo. Más resultados.",
  },
  nav: [
    { id: "demo", label: "Demo", href: "#personalized-demo" },
    { id: "fit", label: "Cómo encaja", href: "#fit" },
    { id: "plans", label: "Planes", href: "#plans" },
    { id: "faq", label: "FAQ", href: "#faq" },
  ],
  navCta: "Crear demo de mi firma",
  common: {
    skipToContent: "Ir al contenido",
    languageLabel: "Cambiar idioma",
    languageEnglish: "English",
    languageSpanish: "Español",
    themeLabel: "Cambiar tema",
    themeSystem: "Sistema",
    themeLight: "Claro",
    themeDark: "Oscuro",
    openMenu: "Abrir menú",
    closeMenu: "Cerrar menú",
  },
  hero: {
    headline: "Automatización creada para bufetes de PIP.",
    supporting: "Llamadas atendidas. Clientes captados. Seguimiento resuelto.",
    selectorQuestion: "¿Qué debería manejar Stellara?",
    services: [
      { id: "after-hours", label: "Llamadas fuera de horario" },
      { id: "reviews", label: "Reseñas" },
      { id: "website-intake", label: "Consultas web" },
      { id: "treatment-follow-up", label: "Seguimiento de tratamiento" },
    ],
  },
  personalizedDemo: {
    eyebrow: "Demo personalizado",
    title: "Ahora véalo funcionando para su firma.",
    description:
      "Ingrese el sitio web de su firma. Crearemos una demo personalizada de admisión de Stellara para que experimente lo que vivirían sus potenciales clientes.",
    fields: {
      websiteLabel: "Sitio web de la firma",
      websitePlaceholder: "https://sufirma.com",
      firstNameLabel: "Nombre",
      firstNamePlaceholder: "Ana",
      lastNameLabel: "Apellido",
      lastNamePlaceholder: "Pérez",
      mobileLabel: "Número móvil",
      mobilePlaceholder: "(000) 000-0000",
      emailLabel: "Correo electrónico",
      emailPlaceholder: "usted@firma.com",
    },
    cta: "Crear demo de mi firma",
    secondaryCta: "Hable con nosotros",
    helperText: "Solo vista previa de interfaz. La entrega real del demo por backend se conectará en la siguiente fase.",
    submittedText: "La captura de solicitud de demo es solo interfaz por ahora. La lógica de envío se conectará después.",
    steps: [
      {
        index: "01",
        title: "Ingrese su sitio web",
        body: "Personalizamos la experiencia alrededor de su firma.",
      },
      {
        index: "02",
        title: "Reciba su demo",
        body: "Le enviaremos por mensaje un enlace privado de demo y un número de prueba.",
      },
      {
        index: "03",
        title: "Conviértase en el cliente",
        body: "Llame a su asistente de admisión con IA, pruebe la experiencia y vea lo que recibiría su equipo.",
      },
    ],
  },
  howItFits: {
    eyebrow: "Cómo encaja",
    title: "Funciona alrededor de su equipo. No en lugar de él.",
    description:
      "Stellara gestiona pasos repetitivos entre la actividad entrante de clientes y los sistemas y el personal que su firma ya utiliza.",
    incoming: ["Llamadas", "Formularios", "Textos", "Sitio web"],
    core: ["Responder", "Calificar", "Dar seguimiento", "Agendar"],
    output: ["CRM", "Calendario", "Su equipo"],
    brandLabel: "Stellara",
    footnote:
      "Su equipo interviene donde se necesita criterio humano. Stellara maneja el trabajo repetitivo alrededor de ellos.",
  },
  measurableWork: {
    eyebrow: "Visibilidad",
    title: "Vea qué se está haciendo.",
    description:
      "Sepa qué se está gestionando, qué necesita atención y dónde podrían estarse perdiendo oportunidades.",
    reportLabel: "Reporte de ejemplo",
    dashboardLabel: "Panel ilustrativo",
    metrics: [
      { label: "Consultas atendidas", value: "146" },
      { label: "Tiempo de respuesta", value: "00:42" },
      { label: "Consultas calificadas", value: "58" },
      { label: "Consultas programadas", value: "31" },
      { label: "Seguimientos completados", value: "82" },
      { label: "Seguimientos de tratamiento", value: "37" },
      { label: "Reseñas solicitadas", value: "49" },
    ],
  },
  plans: {
    eyebrow: "Planes",
    title: "Comience con los flujos de trabajo que más importan.",
    description: "Dos puntos de partida claros con precios de fundadores. Elija primero la profundidad de flujos que necesita su firma.",
    badge: "Precios de fundadores · primeras 5 firmas",
    monthlyPriceLabel: "Precio mensual",
    implementationLabel: "Implementación (pago único)",
    featureHeader: "Característica",
    essentialsLabel: "Essentials",
    proLabel: "Pro",
    includedEssentialsAria: "Incluido en Essentials",
    notIncludedEssentialsAria: "No incluido en Essentials",
    includedProAria: "Incluido en Pro",
    notIncludedProAria: "No incluido en Pro",
    distinction:
      "La diferencia: Essentials captura consultas, agenda citas y solicita reseñas. Pro agrega admisión web y seguimiento continuo de prospectos y clientes potenciales.",
    addOnsLabel: "Complementos opcionales (hasta 3)",
    primaryCta: "Ver Stellara en acción",
    secondaryCta: "Hable con nosotros",
    plans: [
      {
        name: "Essentials",
        monthly: "$497",
        implementation: "$500",
        summary: "Captura consultas, agenda citas y solicita reseñas.",
        points: [
          "Atención de llamadas con IA / admisión fuera de horario",
          "Recuperación de llamadas perdidas / respuesta por texto",
          "Agendamiento de consultas y recordatorios",
          "Solicitudes automáticas de reseñas",
          "Reporte mensual de resultados",
        ],
      },
      {
        name: "Pro",
        highlighted: true,
        monthly: "$997",
        implementation: "$1,000",
        summary: "Agrega admisión web y seguimiento continuo de prospectos y clientes potenciales.",
        points: [
          "Todo lo incluido en Essentials",
          "Agente de admisión web con IA",
          "Seguimiento y reactivación de prospectos",
          "Seguimiento de tratamiento",
          "Visibilidad del pipeline de prospectos/clientes",
        ],
      },
    ],
    addOns: [
      "Mejora inteligente del sitio web",
      "Reactivación de consultas no convertidas",
      "Integración personalizada de admisión y sistema de casos",
    ],
    features: [
      { label: "Atención de llamadas con IA / admisión fuera de horario", essentials: true, pro: true },
      { label: "Recuperación de llamadas perdidas / respuesta por texto", essentials: true, pro: true },
      { label: "Agendamiento de consultas y recordatorios", essentials: true, pro: true },
      { label: "Solicitudes automáticas de reseñas", essentials: true, pro: true },
      { label: "Reporte mensual de resultados", essentials: true, pro: true },
      { label: "Agente de admisión web con IA", essentials: false, pro: true },
      { label: "Seguimiento y reactivación de prospectos", essentials: false, pro: true },
      { label: "Seguimiento de tratamiento", essentials: false, pro: true },
      { label: "Visibilidad del pipeline de prospectos/clientes", essentials: false, pro: true },
    ],
  },
  trustFounder: {
    eyebrow: "Confianza",
    title: "Construido de forma diferente, a propósito.",
    description:
      "Especializado, práctico y enfocado intencionalmente en los flujos que las firmas boutique de PIP necesitan mover cada día.",
    imagePlaceholder: "Espacio para fotografía real del fundador",
    paragraphOne:
      "Stellara se construyó alrededor de una idea simple: las firmas no deberían necesitar equipos más grandes para ofrecer experiencias de cliente ágiles y consistentes.",
    paragraphTwo:
      "Combinamos software, automatización e IA alrededor de los flujos que su firma ya utiliza, y luego medimos si el trabajo realmente se está haciendo.",
    tagline: "Boutique por diseño. Práctico por defecto.",
  },
  faqFinalCta: {
    eyebrow: "FAQ",
    title: "Preguntas antes de probarlo",
    description:
      "Respuestas claras y prácticas. Los detalles finales de implementación se definen con su firma antes del lanzamiento.",
    faqs: [
      {
        q: "¿Stellara reemplaza a nuestro equipo de admisión?",
        a: "No. Stellara está diseñado para gestionar pasos repetitivos de flujo y transferir a su equipo cuando se necesita criterio humano.",
      },
      {
        q: "¿Qué pasa cuando una conversación necesita a una persona?",
        a: "Las rutas de transferencia a humanos se configuran durante la implementación. Las reglas finales de escalamiento se definen con su equipo.",
      },
      {
        q: "¿Podemos decidir qué consultas cumplen nuestros criterios de admisión?",
        a: "Sí. Los criterios de admisión los define su firma y se revisan en la configuración antes de finalizar los flujos.",
      },
      {
        q: "¿Stellara puede atender en español?",
        a: "Los flujos en español pueden configurarse durante la implementación. La cobertura exacta de idiomas se confirma en el alcance de su proyecto.",
      },
      {
        q: "¿Stellara puede trabajar con nuestros sistemas actuales?",
        a: "El alcance de integración varía por firma. Primero se revisan sus sistemas y luego se definen rutas de integración viables.",
      },
      {
        q: "¿Cuánto tarda la implementación?",
        a: "El tiempo depende de los flujos seleccionados y la profundidad de integración. Se entrega un plan claro antes de iniciar.",
      },
      {
        q: "¿Qué podemos medir?",
        a: "Puede medir actividad operativa como consultas atendidas, seguimientos completados y resultados de programación. El reporte exacto se define con su equipo.",
      },
    ],
    finalTitle: "Vea a Stellara trabajando para su firma.",
    finalDescription: "Experimente su propio flujo de admisión antes de tener que hablar con nosotros.",
    primaryCta: "Crear demo de mi firma",
    secondaryCta: "Hable con nosotros",
  },
  explorer: {
    q3: {
      prompt: "¿Qué resultado es más importante?",
      options: [
        { id: "faster", label: "Responder más rápido" },
        { id: "booked", label: "Más citas agendadas" },
        { id: "fewer", label: "Menos tareas repetitivas" },
        { id: "experience", label: "Mejor experiencia del cliente" },
        { id: "visibility", label: "Mayor visibilidad operativa" },
        { id: "custom", label: "Un sistema hecho a nuestro flujo" },
      ],
    },
    componentsLabel: "Componentes probables",
    recommendations: [
      {
        id: "reception",
        title: "Recepción con IA y captura de prospectos",
        why: "Cuando las consultas y llamadas se escapan, la prioridad es asegurar que cada oportunidad se responda, se entienda y se dirija.",
        components: ["Recepcionista telefónico con IA", "Agente conversacional web", "Recuperación de llamadas perdidas"],
      },
      {
        id: "speed",
        title: "Respuesta inmediata y seguimiento",
        why: "Cuando llega el interés pero la respuesta es lenta o dispareja, la rapidez consistente y el seguimiento estructurado recuperan oportunidades ya ganadas.",
        components: ["Respuesta inmediata a prospectos", "Calificación de prospectos", "Seguimiento por correo y SMS"],
      },
      {
        id: "appointment",
        title: "Coordinación de citas",
        why: "Cuando agendar depende del ida y vuelta, la coordinación automatizada concreta más de las reuniones que ya intenta programar.",
        components: ["Agendamiento de citas", "Confirmaciones y recordatorios", "Recuperación de ausencias"],
      },
      {
        id: "support",
        title: "Atención al cliente con IA",
        why: "Cuando las preguntas frecuentes consumen a su equipo, un agente que trabaja con conocimiento aprobado resuelve las comunes y deriva el resto.",
        components: ["Atención al cliente con IA", "Base de conocimiento aprobada", "Escalamiento a personas"],
      },
      {
        id: "workflow",
        title: "Automatización de flujos",
        why: "Cuando la administración repetitiva frena la ejecución, automatizar los pasos entre sistemas elimina fricción sin sumar otra plataforma que gestionar.",
        components: ["Orquestación de flujos", "Notificaciones internas", "Informes operativos"],
      },
      {
        id: "integration",
        title: "Integración de sistemas",
        why: "Cuando las herramientas no se comunican, conectarlas elimina la copia manual que genera demoras y errores.",
        components: ["Integración de sistemas", "Sincronización de datos", "APIs"],
      },
      {
        id: "software",
        title: "Descubrimiento de software a medida",
        why: "Cuando ninguna herramienta existente encaja con su forma de trabajar, un descubrimiento enfocado define si el software a medida es la inversión adecuada.",
        components: ["Taller de descubrimiento", "Mapeo de procesos", "Alcance de la aplicación"],
      },
    ],
    routing: {
      inquiries: "reception",
      followup: "speed",
      scheduling: "appointment",
      support: "support",
      admin: "workflow",
      systems: "integration",
      unsure: "software",
    },
  },
  appointment: {
    title: "Encontremos el punto de partida adecuado.",
    reassurance:
      "Sin discursos genéricos sobre IA. Hablaremos del trabajo, del obstáculo y de si la automatización o el software a medida realmente tiene sentido.",
    step: "Paso",
    of: "de",
    steps: { reason: "Motivo", contact: "Contacto", time: "Horario", confirm: "Confirmar" },
    reasonOptions: [
      { id: "agents", label: "Agentes de IA" },
      { id: "workflow", label: "Automatización de flujos" },
      { id: "software", label: "Software a medida" },
      { id: "integration", label: "Integración de sistemas" },
      { id: "unsure", label: "Aún no estoy seguro" },
    ],
    fields: {
      name: "Nombre",
      email: "Correo de trabajo",
      company: "Empresa",
      phone: "Teléfono",
      website: "Sitio web",
      language: "Idioma preferido",
      description: "Breve descripción del problema operativo",
      optional: "opcional",
    },
    placeholders: {
      name: "Su nombre",
      email: "usted@empresa.com",
      company: "Nombre de la empresa",
      phone: "(000) 000-0000",
      website: "https://",
      description: "Qué suele detenerse y qué le gustaría mejorar.",
    },
    timeIntro: "Elija un horario que le convenga para una breve llamada introductoria.",
    timeNote: "Los horarios son ilustrativos y se muestran en su zona horaria local. Confirmaremos el horario exacto por correo.",
    pickDay: "Seleccione un día",
    pickTime: "Seleccione un horario",
    consent: "Al enviar este formulario, acepta que Stellara se comunique con usted acerca de su consulta. Consulte nuestra",
    privacyLink: "Política de Privacidad",
    next: "Continuar",
    back: "Atrás",
    submit: "Solicitar este horario",
    submitting: "Enviando…",
    confirmTitle: "Solicitud recibida",
    confirmReason: "Motivo",
    confirmTime: "Horario solicitado",
    confirmEmail: "Correo de contacto",
    whatNext: "Qué esperar",
    whatNextBody:
      "Confirmaremos su horario por correo y compartiremos una breve agenda enfocada en el trabajo que describió. No requiere preparación.",
    close: "Cerrar",
    errors: {
      name: "Ingrese su nombre.",
      email: "Ingrese su correo de trabajo.",
      emailInvalid: "Ingrese un correo electrónico válido.",
      company: "Ingrese su empresa.",
      reason: "Elija un motivo para la conversación.",
      time: "Seleccione un día y un horario.",
      consent: "Acepte el consentimiento de contacto para continuar.",
    },
  },
  assistant: {
    launcherLabel: "Abrir el asistente de Stellara",
    title: "Asistente de Stellara",
    intro:
      "Hola. Puedo ayudarle a explorar dónde la automatización o el software a medida podría ser útil. ¿Dónde suele detenerse el trabajo?",
    quickReplies: [
      { id: "inquiries", label: "Llamadas perdidas" },
      { id: "followup", label: "Seguimiento de prospectos" },
      { id: "scheduling", label: "Programación de citas" },
      { id: "support", label: "Atención al cliente" },
      { id: "admin", label: "Administración repetitiva" },
      { id: "systems", label: "Sistemas desconectados" },
      { id: "unsure", label: "Otro tema" },
    ],
    followUp: "Entendido. ¿Y qué resultado es el más importante?",
    recommendPrefix: "En base a eso, un punto de partida sensato es",
    whyPrefix: "Por qué:",
    bookCta: "Abrir el agendamiento",
    restart: "Comenzar de nuevo",
    restartLabel: "Reiniciar conversación",
    closeLabel: "Cerrar asistente",
    disclaimer: "Esta es una guía interactiva, no un agente humano, y no puede acceder a datos privados de la empresa.",
    guideNote: "Demostración guiada",
  },
  footer: {
    descriptor: "Automatización con IA y software a medida para el trabajo que impulsa su empresa.",
    navTitle: "Explorar",
    contactTitle: "Contacto",
    contactPlaceholder: "Iniciar una conversación",
    legalTitle: "Legal",
    privacy: "Privacidad",
    terms: "Términos",
    crafted: "Concebido en el Hudson Valley.",
    rights: "Todos los derechos reservados.",
  },
  whatsapp: {
    label: "Contactar a Stellara por WhatsApp",
    message: "Hola, me interesa conocer cómo Stellara podría ayudar a automatizar un proceso en mi empresa.",
    cta: "WhatsApp",
  },
  privacy: {
    title: "Política de Privacidad",
    updated: "Última actualización",
    reviewNote: "Esta es una plantilla base. Los campos marcados para revisión requieren una revisión legal específica del negocio antes de publicarse.",
    intro:
      "Esta política explica, en lenguaje claro, cómo Stellara maneja la información compartida a través de este sitio web. Es una plantilla inicial y debe ser revisada por un asesor legal calificado antes de utilizarse.",
    sections: [
      {
        heading: "Información que recopilamos",
        body: [
          "Recopilamos la información que usted decide proporcionar mediante nuestros formularios de contacto y agendamiento, como su nombre, correo de trabajo, empresa y una descripción de su problema operativo.",
          "Podemos recopilar información técnica limitada (como eventos generales de analítica) que no incluye datos de identificación personal.",
        ],
      },
      {
        heading: "Cómo usamos la información",
        body: [
          "Usamos la información que proporciona para responder a su consulta, preparar una conversación y dar seguimiento al trabajo que describió.",
          "No vendemos su información. [Revisión: confirme los compromisos de manejo de datos con un asesor legal.]",
        ],
      },
      {
        heading: "Conservación de datos",
        body: ["[Revisión: defina los períodos de conservación apropiados para su jurisdicción y negocio.]"],
      },
      {
        heading: "Sus opciones",
        body: ["Puede solicitar acceso o eliminación de la información que compartió contactándonos. [Revisión: confirme los derechos aplicables.]"],
      },
      {
        heading: "Contacto",
        body: ["Las preguntas sobre esta política pueden dirigirse al canal de contacto indicado en este sitio."],
      },
    ],
    backHome: "Volver al inicio",
  },
  terms: {
    title: "Términos del Servicio",
    updated: "Última actualización",
    reviewNote: "Esta es una plantilla base. Los campos marcados para revisión requieren una revisión legal específica del negocio antes de publicarse.",
    intro:
      "Estos términos describen, en lenguaje claro, la base sobre la cual se ofrece este sitio web. Son una plantilla inicial y deben ser revisados por un asesor legal calificado antes de utilizarse.",
    sections: [
      {
        heading: "Uso de este sitio web",
        body: [
          "Este sitio web se ofrece con fines de información general sobre los servicios de Stellara. El contenido puede cambiar sin previo aviso.",
          "Nada en este sitio constituye una oferta vinculante, garantía o promesa de resultados específicos.",
        ],
      },
      {
        heading: "Consultas y citas",
        body: [
          "Enviar un formulario o solicitar una cita inicia una conversación y no crea un contrato de servicios.",
          "[Revisión: agregue términos de contratación, alcance y pago con un asesor legal.]",
        ],
      },
      {
        heading: "Propiedad intelectual",
        body: ["El nombre Stellara, el logotipo y los materiales de marca son propiedad de Stellara. [Revisión: confirme con un asesor legal.]"],
      },
      {
        heading: "Limitación de responsabilidad",
        body: ["[Revisión: agregue un texto de limitación de responsabilidad apropiado para su jurisdicción con un asesor legal.]"],
      },
      {
        heading: "Contacto",
        body: ["Las preguntas sobre estos términos pueden dirigirse al canal de contacto indicado en este sitio."],
      },
    ],
    backHome: "Volver al inicio",
  },
}
