import type { SiteContent } from "./schema"

export const es: SiteContent = {
  locale: "es",
  meta: {
    title: "Stellara | Automatización con IA y software a medida",
    description:
      "Stellara diseña agentes de IA, flujos conectados y software a medida para ayudar a las empresas a responder más rápido, operar con claridad y aprovechar más oportunidades.",
    ogTitle: "Stellara — Automatizamos el trabajo que mueve su negocio.",
    ogDescription:
      "Agentes de IA, flujos conectados y software a medida, creados en el Hudson Valley de Nueva York. Menos humo. Más resultados.",
  },
  nav: [
    { id: "demo", label: "Demo", href: "#personalized-demo" },
    { id: "fit", label: "Cómo encaja", href: "#fit" },
    { id: "plans", label: "Planes", href: "#plans" },
    { id: "faq", label: "FAQ", href: "#faq" },
  ],
  navCta: "Crear demo de mi firma",
  common: {
    skipToContent: "Ir al contenido",
    languageLabel: "Cambiar idioma",
    languageEnglish: "English",
    languageSpanish: "Español",
    themeLabel: "Cambiar tema",
    themeSystem: "Sistema",
    themeLight: "Claro",
    themeDark: "Oscuro",
    openMenu: "Abrir menú",
    closeMenu: "Cerrar menú",
  },
  hero: {
    headline: "Automatización creada para bufetes de PIP.",
    supporting: "Llamadas atendidas. Clientes captados. Seguimiento resuelto.",
    selectorQuestion: "¿Qué debería manejar Stellara?",
    services: [
      { id: "after-hours", label: "Llamadas fuera de horario" },
      { id: "reviews", label: "Reseñas" },
      { id: "website-intake", label: "Consultas web" },
      { id: "treatment-follow-up", label: "Seguimiento de tratamiento" },
    ],
  },
  personalizedDemo: {
    eyebrow: "Demo personalizado",
    title: "Ahora véalo funcionando para su firma.",
    description:
      "Ingrese el sitio web de su firma. Crearemos una demo personalizada de admisión de Stellara para que experimente lo que vivirían sus potenciales clientes.",
    fields: {
      websiteLabel: "Sitio web de la firma",
      websitePlaceholder: "https://sufirma.com",
      firstNameLabel: "Nombre",
      firstNamePlaceholder: "Ana",
      lastNameLabel: "Apellido",
      lastNamePlaceholder: "Pérez",
      mobileLabel: "Número móvil",
      mobilePlaceholder: "(000) 000-0000",
      emailLabel: "Correo electrónico",
      emailPlaceholder: "usted@firma.com",
    },
    cta: "Crear demo de mi firma",
    secondaryCta: "Hable con nosotros",
    helperText: "Solo vista previa de interfaz. La entrega real del demo por backend se conectará en la siguiente fase.",
    submittedText: "La captura de solicitud de demo es solo interfaz por ahora. La lógica de envío se conectará después.",
    steps: [
      {
        index: "01",
        title: "Ingrese su sitio web",
        body: "Personalizamos la experiencia alrededor de su firma.",
      },
      {
        index: "02",
        title: "Reciba su demo",
        body: "Le enviaremos por mensaje un enlace privado de demo y un número de prueba.",
      },
      {
        index: "03",
        title: "Conviértase en el cliente",
        body: "Llame a su asistente de admisión con IA, pruebe la experiencia y vea lo que recibiría su equipo.",
      },
    ],
  },
  howItFits: {
    eyebrow: "Cómo encaja",
    title: "Funciona alrededor de su equipo. No en lugar de él.",
    description:
      "Stellara gestiona pasos repetitivos entre la actividad entrante de clientes y los sistemas y el personal que su firma ya utiliza.",
    takeaway: "Los pasos rutinarios siguen avanzando. Su equipo se mantiene informado y en control.",
    illustrative: "Flujo ilustrativo · datos ficticios",
    scenarioLabel: "Elija un flujo",
    replay: "Repetir",
    replayLabel: "Repetir este flujo",
    ownerLabels: {
      auto: "Gestionado automáticamente",
      handoff: "Requiere acción del personal",
      staff: "Su equipo decide",
    },
    nextLabel: "Siguiente acción",
    scenarios: [
      {
        id: "new-inquiry",
        label: "Nueva consulta",
        steps: [
          {
            stage: "Llega una consulta",
            owner: "auto",
            title: "Daniel Ortiz",
            meta: "Formulario web · 7:48 p. m.",
            lines: ["\u201CMe chocaron por detrás la semana pasada y estoy viendo a un quiropráctico.\u201D"],
          },
          {
            stage: "Stellara gestiona el siguiente paso",
            owner: "auto",
            title: "Datos básicos recopilados",
            meta: "7:49 p. m.",
            lines: ["Fecha del accidente: 24 sep", "En tratamiento: Sí", "Prefiere llamada después de las 9 a. m."],
          },
          {
            stage: "Su equipo recibe el contexto",
            owner: "handoff",
            title: "Equipo de admisión notificado",
            meta: "7:50 p. m.",
            lines: ["Choque por detrás, en tratamiento quiropráctico", "Sin abogado actual"],
            next: "Revisar y responder",
          },
          {
            stage: "Su personal toma el control",
            owner: "staff",
            title: "Ana revisa la consulta",
            meta: "8:15 a. m.",
            lines: ["Llama a Daniel para hablar de los próximos pasos"],
          },
        ],
      },
      {
        id: "treatment-follow-up",
        label: "Seguimiento de tratamiento",
        steps: [
          {
            stage: "Se envía un seguimiento",
            owner: "auto",
            title: "Jane Doe",
            meta: "Texto programado · jue 10:00 a. m.",
            lines: ["\u201CHola Jane, queremos saber cómo va su tratamiento.\u201D"],
          },
          {
            stage: "Llega una respuesta",
            owner: "auto",
            title: "Menciona una cita perdida",
            meta: "jue 10:12 a. m.",
            lines: ["\u201CFalté a terapia el martes. Problemas con el auto.\u201D"],
          },
          {
            stage: "Su equipo recibe el contexto",
            owner: "handoff",
            title: "Marcado para seguimiento",
            meta: "jue 10:12 a. m.",
            lines: ["Faltó a terapia física el martes", "Motivo: transporte"],
            next: "Llamar para ayudar a reprogramar",
          },
          {
            stage: "Su personal toma el control",
            owner: "staff",
            title: "Ana llama a Jane",
            meta: "jue 10:40 a. m.",
            lines: ["La ayuda a retomar su tratamiento"],
          },
        ],
      },
      {
        id: "review-request",
        label: "Solicitud de reseña",
        steps: [
          {
            stage: "Se alcanza un hito",
            owner: "auto",
            title: "John Doe",
            meta: "Caso cerrado · lun 2:10 p. m.",
            lines: ["Regla de la firma: solicitar reseña al cerrar un caso"],
          },
          {
            stage: "Stellara envía la solicitud",
            owner: "auto",
            title: "Solicitud neutral enviada",
            meta: "lun 2:11 p. m.",
            lines: ["La misma solicitud para cada cliente en este hito", "Un recordatorio si no hay respuesta"],
          },
          {
            stage: "Su equipo recibe el contexto",
            owner: "handoff",
            title: "Respuesta que requiere atención",
            meta: "mar 9:05 a. m.",
            lines: ["\u201C¿Alguien puede llamarme sobre mis documentos finales?\u201D"],
            next: "Responder personalmente",
          },
          {
            stage: "Su personal toma el control",
            owner: "staff",
            title: "Ana responde",
            meta: "mar 9:30 a. m.",
            lines: ["Llama a John sobre sus documentos"],
          },
        ],
      },
    ],
    footnote:
      "Su equipo interviene donde se necesita criterio humano. Stellara maneja el trabajo repetitivo alrededor de ellos.",
  },
  measurableWork: {
    eyebrow: "A la mañana siguiente",
    title: "Lo que avanzó. Lo que necesita su equipo.",
    description:
      "Cada mañana su equipo ve lo que Stellara gestionó durante la noche y exactamente qué asuntos esperan a una persona.",
    illustrative: "Ejemplo ilustrativo · firma y datos ficticios",
    briefLabel: "Resumen matutino",
    briefFirm: "ABC Law",
    briefTime: "Martes · 7:30 a. m.",
    movedLabel: "Avanzó",
    actionLabel: "Su equipo",
    handoffStatus: "Requiere acción del personal",
    doneStatus: "No requiere acción",
    items: [
      {
        count: "6",
        label: "Consultas captadas durante la noche",
        detail: "Datos recopilados y equipo de admisión notificado.",
        action: "Devolver la llamada a las 2 personas que pidieron hablar después de las 9 a. m.",
        tone: "handoff",
      },
      {
        count: "3",
        label: "Consultas programadas",
        detail: "Confirmaciones enviadas. Los recordatorios están programados.",
        action: "Ya están en el calendario de hoy.",
        tone: "done",
      },
      {
        count: "2",
        label: "Respuestas de clientes que requieren seguimiento",
        detail: "Jane D. mencionó que faltó a una cita de fisioterapia.",
        action: "Ana llama a Jane para ayudarle a reprogramar.",
        tone: "handoff",
      },
      {
        count: "4",
        label: "Solicitudes de reseña enviadas",
        detail: "Enviadas a clientes cuyos casos se cerraron ayer.",
        action: "Se envía un recordatorio si no hay respuesta.",
        tone: "done",
      },
    ],
    monthLabel: "Durante el mes",
    monthPeriod: "Últimos 30 días",
    monthMetrics: [
      { label: "Consultas atendidas", value: "146" },
      { label: "Consultas programadas", value: "31" },
      { label: "Seguimientos completados", value: "82" },
      { label: "Asuntos pendientes", value: "5" },
    ],
    footnote:
      "Estas cifras muestran la actividad de los flujos que su firma puede revisar. No son resultados de una firma real y no miden el valor de los casos ni los ingresos.",
    dashboard: {
      title: "Panel",
      live: "En vivo",
      nav: ["Panel", "Conversaciones", "Calendarios", "Contactos", "Tareas", "Agentes"],
      todayLabel: "hoy",
      sourceTitle: "Contactos por origen",
      sources: [
        { label: "Widget web", value: 58 },
        { label: "Chat fuera de horario", value: 41 },
        { label: "Teléfono", value: 29 },
        { label: "Referido", value: 18 },
      ],
      statusTitle: "Contactos por estado",
      statusTotal: "contactos",
      statuses: [
        { label: "Activos", value: 64 },
        { label: "Nuevos", value: 46 },
        { label: "Con cita", value: 31 },
        { label: "Requieren personal", value: 5 },
      ],
      growthTitle: "Crecimiento de contactos",
      growthPeriod: "Últimos 14 días",
      growth: [4, 6, 5, 8, 7, 9, 12, 10, 11, 14, 13, 16, 15, 19],
      activityTitle: "Actividad nocturna",
      events: [
        "Stellara captó una nueva consulta desde el widget web",
        "Stellara programó una consulta para las 10:30 AM",
        "Stellara envió un seguimiento de tratamiento",
        "Stellara marcó una respuesta del cliente para Ana",
      ],
    },
  },
  stories: {
    controls: {
      previous: "Escena anterior",
      next: "Escena siguiente",
      progress: "Escena {current} de {total}",
      illustrative: "Ejemplo ilustrativo · datos ficticios",
      handledAutomatically: "Gestionado automáticamente",
      staffActionNeeded: "Requiere acción del personal",
      intakeAriaLabel: "Admisión 24/7: cómo Stellara atiende consultas cuando su oficina está cerrada",
    },
    treatment: {
      ariaLabel: "Seguimiento de tratamiento: cómo una cita perdida se convierte en un siguiente paso visible para su equipo",
      scenes: [
        {
          time: "Mar 3:00 PM",
          step: "Calendario",
          title: "Cita perdida",
          headline: "La vida interrumpe la agenda.",
          body: "Sin transporte, no hay cita. Pasa.",
          summary: "Jane Doe pierde su cita de terapia física del martes porque no consiguió transporte.",
        },
        {
          time: "Jue 10:00 AM",
          step: "Seguimiento",
          title: "Mensaje programado enviado",
          headline: "Stellara hace el seguimiento.",
          body: "Sale un mensaje programado. Nadie de su equipo tiene que escribirlo.",
          summary: "A la hora programada, Jane recibe un mensaje que le pregunta si pudo asistir a su cita.",
        },
        {
          time: "Jue 10:12 AM",
          step: "Respuesta",
          title: "El cliente responde",
          headline: "El cliente explica.",
          body: "Las respuestas llegan con las palabras del cliente.",
          summary: "Jane responde: No pude ir. No conseguí transporte.",
        },
        {
          time: "Jue 10:12 AM",
          step: "Alerta",
          title: "Equipo alertado",
          headline: "Su equipo ve lo que requiere atención.",
          body: "La respuesta se convierte en una alerta con contexto y un siguiente paso.",
          summary: "El equipo ve una alerta con la respuesta de Jane, la cita perdida y el siguiente paso: dar seguimiento al cliente.",
        },
        {
          time: "Jue 10:40 AM",
          step: "Contacto",
          title: "El equipo contacta al cliente",
          headline: "Su equipo da el siguiente paso.",
          body: "Seguimientos constantes. Visibilidad temprana. Un siguiente paso claro.",
          summary: "Un miembro del equipo llama a Jane y el estado cambia a Equipo contactó al cliente.",
        },
      ],
      ui: {
        clientName: "Jane Doe",
        clientTag: "Cliente",
        staffTag: "Su equipo",
        weekLabel: "Esta semana",
        days: ["Mar", "Mié", "Jue"],
        dates: ["15", "16", "17"],
        appointment: "Terapia física",
        appointmentTime: "3:00 PM",
        missed: "Perdida",
        checkinLabel: "Seguimiento programado",
        checkinTime: "Jue 10:00 AM",
        autoSent: "Enviado automáticamente",
        firm: "ABC Law",
        question: "Hola Jane, le escribe ABC Law. ¿Pudo asistir a su cita?",
        reply: "No pude ir. No conseguí transporte.",
        replyTime: "10:12 AM",
        alertTitle: "Requiere atención",
        alertContext: ["Perdió terapia física el martes", "Motivo: sin transporte"],
        nextActionLabel: "Siguiente paso",
        nextAction: "Dar seguimiento al cliente",
        statusLabel: "Estado",
        statusDone: "Equipo contactó al cliente",
      },
    },
    reviews: {
      ariaLabel: "Reseñas: cómo pedir opiniones de forma constante puede ayudar a un posible cliente a decidirse a contactar",
      illustrative: "Recorrido ilustrativo \u00B7 firma, personas y reseña ficticias",
      scenes: [
        {
          time: "Lun 2:10 PM",
          step: "Etapa",
          title: "Etapa alcanzada",
          headline: "Llega el momento adecuado.",
          body: "Una etapa que define su firma activa una solicitud de reseña neutral.",
          summary: "Un miembro del equipo marca como cerrado el caso de John Doe, lo que coincide con la regla de reseñas de la firma.",
        },
        {
          time: "Lun 2:11 PM",
          step: "Invitación",
          title: "Solicitud entregada",
          headline: "Sale la invitación.",
          body: "El mismo texto para cada cliente. Sin calificación preseleccionada.",
          summary: "John recibe un mensaje que lo invita a compartir su experiencia, con un enlace para dejar una reseña.",
        },
        {
          time: "Lun 6:30 PM",
          step: "Opinión",
          title: "El cliente comparte su opinión",
          headline: "Un cliente comparte su experiencia.",
          body: "Con sus propias palabras, si así lo decide.",
          summary: "John publica una reseña ilustrativa: El equipo me explicó los siguientes pasos y me mantuvo informado.",
        },
        {
          time: "Semanas después",
          step: "Búsqueda",
          title: "Alguien busca",
          headline: "Alguien busca una firma.",
          body: "Otra persona busca ayuda y encuentra su ficha.",
          summary: "Semanas después, un posible cliente busca un abogado de accidentes de auto y ve la ficha de ABC Law con reseñas.",
        },
        {
          time: "Semanas después",
          step: "Evaluación",
          title: "Lee las reseñas",
          headline: "Se detiene a leer.",
          body: "Las experiencias de otros clientes le ayudan a decidir.",
          summary: "El posible cliente abre las reseñas de la firma y lee cómo el equipo mantuvo informado a un cliente.",
        },
        {
          time: "Semanas después",
          step: "Contacto",
          title: "Solicita una consulta",
          headline: "Da el siguiente paso.",
          body: "Pida opiniones de forma constante. Ayude a los posibles clientes a elegir con más confianza.",
          summary: "El posible cliente solicita una consulta y una notificación de la solicitud llega a la firma.",
        },
      ],
      ui: {
        clientTag: "Cliente actual",
        prospectTag: "Posible cliente",
        staffTag: "Su equipo",
        firmTag: "Su firma",
        differentPerson: "Otra persona",
        matterName: "John Doe",
        matterType: "Accidente de auto",
        milestones: ["Expedientes reunidos", "Reclamo enviado", "Caso cerrado"],
        ruleMatched: "Regla de la firma: pedir reseña",
        firm: "ABC Law",
        lockTime: "6:30",
        now: "ahora",
        request: "Gracias por elegir ABC Law, John. ¿Compartiría su experiencia?",
        linkTitle: "Comparta su experiencia",
        linkLabel: "Enlace para reseña",
        reviewerInitials: "JD",
        reviewerName: "John D.",
        reviewText: "El equipo me explicó los siguientes pasos y me mantuvo informado.",
        reviewLabel: "Reseña ilustrativa",
        post: "Publicar",
        posted: "Publicada",
        searchQuery: "abogado accidente de auto cerca",
        listingMeta: "Lesiones personales",
        reviewsLink: "Reseñas",
        tabs: ["Resumen", "Reseñas", "Sitio web"],
        consultCta: "Solicitar una consulta",
        notificationTitle: "Nueva solicitud de consulta",
        notificationSource: "Desde el perfil de su firma",
        requested: "Solicitada",
      },
    },
    website: {
      ariaLabel: "Formulario web: cómo la pregunta de un visitante se convierte en una solicitud útil para su equipo",
      scenes: [
        {
          time: "8:47 PM",
          step: "Visita",
          title: "Llega un visitante",
          headline: "Alguien llega con una pregunta.",
          body: "Un posible cliente encuentra el sitio web de su firma.",
          summary: "Un posible cliente navega por el sitio web de ABC Law por la noche.",
        },
        {
          time: "8:48 PM",
          step: "Pregunta",
          title: "Abre el asistente",
          headline: "Hay una forma clara de preguntar.",
          body: "El asistente de admisión le da un lugar sencillo para empezar.",
          summary: "El visitante abre el asistente de admisión y pregunta: ¿Alguien me puede contactar por un accidente de auto?",
        },
        {
          time: "8:49 PM",
          step: "Datos",
          title: "Datos básicos reunidos",
          headline: "Se reúnen los datos básicos.",
          body: "Unas preguntas breves completan los datos de forma ordenada.",
          summary: "El visitante comparte su nombre, tipo de caso, fecha del accidente y teléfono, que completan una solicitud ordenada.",
        },
        {
          time: "8:50 PM",
          step: "Llamada",
          title: "Consulta solicitada",
          headline: "Se solicita una consulta.",
          body: "El visitante elige un horario preferido. Su equipo lo confirma.",
          summary: "El visitante pide que lo llamen el jueves a las 11:00 AM. Queda como Solicitada hasta que la firma confirme.",
        },
        {
          time: "Vie 8:00 AM",
          step: "Resumen",
          title: "El equipo recibe el contexto",
          headline: "Su equipo recibe el contexto.",
          body: "Dé a los visitantes un siguiente paso. Dé a su equipo el contexto.",
          summary: "El equipo ve un resumen breve de la solicitud con un siguiente paso: llamar para confirmar la consulta.",
        },
      ],
      ui: {
        url: "abclaw.com",
        siteName: "ABC Law",
        siteHeadline: "¿Sufrió un accidente de auto?",
        siteCta: "Contáctenos",
        visitorTag: "Visitante",
        staffTag: "Su equipo",
        launcher: "Hacer una pregunta",
        assistantTitle: "Agente de admisión de Stellara",
        question: "¿Alguien me puede contactar por un accidente de auto?",
        assistantReply: "Sí. Unos datos breves ayudarán al equipo a darle seguimiento.",
        detailsPrompt: "Unos datos breves para el equipo:",
        formTitle: "Solicitud",
        fields: [
          { label: "Nombre", value: "Daniel Ortiz" },
          { label: "Caso", value: "Accidente de auto" },
          { label: "Fecha", value: "24 sep" },
          { label: "Teléfono", value: "(845) 555-0142" },
        ],
        callbackTitle: "Horario preferido para la llamada",
        callbackDay: "Jueves",
        slots: ["9:30 AM", "11:00 AM", "2:00 PM"],
        selectedSlot: 1,
        requested: "Solicitada",
        requestedNote: "La firma la confirmará",
        inboxTitle: "Solicitudes",
        inbox: ["Daniel Ortiz", "Priya Shah", "Leo Grant"],
        summaryTitle: "Solicitud desde el sitio web",
        newLabel: "Nueva",
        summary: [
          { label: "Contacto", value: "Daniel Ortiz \u00B7 (845) 555-0142" },
          { label: "Caso", value: "Accidente de auto \u00B7 24 sep" },
          { label: "Llamada", value: "Jue 11:00 AM \u00B7 solicitada" },
        ],
        nextActionLabel: "Siguiente paso",
        nextAction: "Llamar para confirmar la consulta",
      },
    },
  },
  plans: {
    eyebrow: "Planes",
    title: "¿Dónde necesita más apoyo su firma?",
    description:
      "Ambos planes mantienen en movimiento las nuevas consultas e incluyen reportes mensuales. Pro extiende la cobertura a su sitio web y al seguimiento posterior.",
    badge: "Precios de fundadores · primeras 5 firmas",
    implementationLabel: "implementación (pago único)",
    perMonthLabel: "/mes",
    includesEssentials: "Todo lo incluido en Essentials",
    addOnsLabel: "Complementos",
    addOnsNote: "Se conversan con usted al definir el alcance de la implementación.",
    primaryCta: "Ver Stellara en acción",
    secondaryCta: "Hable con nosotros",
    essentials: {
      name: "Essentials",
      focus: "Captar consultas, agendar citas y solicitar reseñas.",
      monthly: "$497",
      implementation: "$500",
      pointsLabel: "Incluye",
      points: [
        "Atención de llamadas con IA / admisión fuera de horario",
        "Recuperación de llamadas perdidas / respuesta por texto",
        "Agendamiento de consultas y recordatorios",
        "Solicitudes automáticas de reseñas",
        "Reporte mensual de resultados",
      ],
    },
    pro: {
      name: "Pro",
      focus: "Todo lo de Essentials, más admisión web y seguimiento continuo de prospectos y clientes.",
      monthly: "$997",
      implementation: "$1,000",
      pointsLabel: "Pro agrega",
      points: [
        "Agente de admisión web con IA",
        "Seguimiento y reactivación de prospectos",
        "Seguimiento de tratamiento",
        "Visibilidad del pipeline de prospectos/clientes",
      ],
    },
    addOns: [
      "Mejora inteligente del sitio web",
      "Reactivaci��n de consultas no convertidas",
      "Integración personalizada de admisión y sistema de casos",
    ],
  },
  trustFounder: {
    eyebrow: "El fundador",
    title: "Conozca a quien construye sus flujos de trabajo.",
    name: "Kerwin Londono",
    role: "Fundador, Stellara AI LLC",
    photo: null,
    photoAlt: "Kerwin Londono, fundador de Stellara AI LLC",
    photoPending: "Foto próximamente",
    paragraphs: [
      "Soy ingeniero de software y creé Stellara para ayudar a las firmas a mantener en movimiento el trabajo rutinario: desde la primera consulta hasta el seguimiento que necesita respuesta.",
      "Empezamos por cómo trabaja su equipo hoy: qué debe ocurrir automáticamente, qué información necesita el personal y en qué momento debe intervenir una persona. Luego configuramos y probamos los flujos acordados y definimos cómo medir su actividad.",
    ],
  },
  faqFinalCta: {
    eyebrow: "FAQ",
    title: "Antes de conectarlo a su firma.",
    description:
      "Respuestas prácticas para dueños de firmas. Los detalles finales se acuerdan con su equipo antes de que algo entre en funcionamiento.",
    groups: [
      {
        label: "Transferencias y criterios",
        items: [
          {
            q: "¿Qué pasa cuando alguien que llama necesita a una persona?",
            a: "Su equipo recibe una notificación con los datos de la persona y lo que se conversó. A quién se notifica, y cuándo, sigue las reglas de transferencia que acordamos con usted durante la implementación.",
          },
          {
            q: "¿Cómo usan nuestros criterios de admisión?",
            a: "Ustedes los definen. Los revisamos con su equipo durante la configuración y los usamos para decidir qué datos se recopilan y qué consultas se señalan al personal. Los flujos se finalizan solo después de su aprobación.",
          },
        ],
      },
      {
        label: "Sistemas e idioma",
        items: [
          {
            q: "¿Puede funcionar con nuestros sistemas actuales?",
            a: "Depende de los sistemas. Primero revisamos lo que usa su firma y luego definimos qué conexiones son viables. Las conexiones más profundas están disponibles con el complemento de Integración personalizada de admisión y sistema de casos.",
          },
          {
            q: "¿Cómo se manejan el inglés y el español?",
            a: "Los flujos en español pueden configurarse durante la implementación. Qué flujos funcionan en español se confirma en el alcance de su configuración.",
          },
        ],
      },
      {
        label: "Implementación y reportes",
        items: [
          {
            q: "¿Qué incluye la implementación?",
            a: "Mapeamos cómo trabaja su equipo hoy, acordamos qué funciona automáticamente y en qué momento interviene el personal, y luego configuramos y probamos esos flujos y definimos cómo medir su actividad. Es un pago único: $500 para Essentials y $1,000 para Pro.",
          },
          {
            q: "¿Qué podremos medir?",
            a: "La actividad de los flujos, incluidas consultas atendidas, consultas programadas, seguimientos completados y asuntos que aún esperan a su equipo. Ambos planes incluyen reporte mensual de resultados, y Pro agrega visibilidad del pipeline de prospectos y clientes.",
          },
        ],
      },
    ],
    finalTitle: "Vea a Stellara trabajando para su firma.",
    finalDescription: "Experimente su propio flujo de admisión antes de tener que hablar con nosotros.",
    primaryCta: "Crear demo de mi firma",
    secondaryCta: "Hable con nosotros",
  },
  explorer: {
    q3: {
      prompt: "¿Qué resultado es más importante?",
      options: [
        { id: "faster", label: "Responder más rápido" },
        { id: "booked", label: "Más citas agendadas" },
        { id: "fewer", label: "Menos tareas repetitivas" },
        { id: "experience", label: "Mejor experiencia del cliente" },
        { id: "visibility", label: "Mayor visibilidad operativa" },
        { id: "custom", label: "Un sistema hecho a nuestro flujo" },
      ],
    },
    componentsLabel: "Componentes probables",
    recommendations: [
      {
        id: "reception",
        title: "Recepción con IA y captura de prospectos",
        why: "Cuando las consultas y llamadas se escapan, la prioridad es asegurar que cada oportunidad se responda, se entienda y se dirija.",
        components: ["Recepcionista telefónico con IA", "Agente conversacional web", "Recuperación de llamadas perdidas"],
      },
      {
        id: "speed",
        title: "Respuesta inmediata y seguimiento",
        why: "Cuando llega el interés pero la respuesta es lenta o dispareja, la rapidez consistente y el seguimiento estructurado recuperan oportunidades ya ganadas.",
        components: ["Respuesta inmediata a prospectos", "Calificación de prospectos", "Seguimiento por correo y SMS"],
      },
      {
        id: "appointment",
        title: "Coordinación de citas",
        why: "Cuando agendar depende del ida y vuelta, la coordinación automatizada concreta más de las reuniones que ya intenta programar.",
        components: ["Agendamiento de citas", "Confirmaciones y recordatorios", "Recuperación de ausencias"],
      },
      {
        id: "support",
        title: "Atención al cliente con IA",
        why: "Cuando las preguntas frecuentes consumen a su equipo, un agente que trabaja con conocimiento aprobado resuelve las comunes y deriva el resto.",
        components: ["Atención al cliente con IA", "Base de conocimiento aprobada", "Escalamiento a personas"],
      },
      {
        id: "workflow",
        title: "Automatización de flujos",
        why: "Cuando la administración repetitiva frena la ejecución, automatizar los pasos entre sistemas elimina fricción sin sumar otra plataforma que gestionar.",
        components: ["Orquestación de flujos", "Notificaciones internas", "Informes operativos"],
      },
      {
        id: "integration",
        title: "Integración de sistemas",
        why: "Cuando las herramientas no se comunican, conectarlas elimina la copia manual que genera demoras y errores.",
        components: ["Integración de sistemas", "Sincronización de datos", "APIs"],
      },
      {
        id: "software",
        title: "Descubrimiento de software a medida",
        why: "Cuando ninguna herramienta existente encaja con su forma de trabajar, un descubrimiento enfocado define si el software a medida es la inversión adecuada.",
        components: ["Taller de descubrimiento", "Mapeo de procesos", "Alcance de la aplicación"],
      },
    ],
    routing: {
      inquiries: "reception",
      followup: "speed",
      scheduling: "appointment",
      support: "support",
      admin: "workflow",
      systems: "integration",
      unsure: "software",
    },
  },
  appointment: {
    title: "Encontremos el punto de partida adecuado.",
    reassurance:
      "Sin discursos genéricos sobre IA. Hablaremos del trabajo, del obstáculo y de si la automatización o el software a medida realmente tiene sentido.",
    step: "Paso",
    of: "de",
    steps: { reason: "Motivo", contact: "Contacto", time: "Horario", confirm: "Confirmar" },
    reasonOptions: [
      { id: "agents", label: "Agentes de IA" },
      { id: "workflow", label: "Automatización de flujos" },
      { id: "software", label: "Software a medida" },
      { id: "integration", label: "Integración de sistemas" },
      { id: "unsure", label: "Aún no estoy seguro" },
    ],
    fields: {
      name: "Nombre",
      email: "Correo de trabajo",
      company: "Empresa",
      phone: "Teléfono",
      website: "Sitio web",
      language: "Idioma preferido",
      description: "Breve descripción del problema operativo",
      optional: "opcional",
    },
    placeholders: {
      name: "Su nombre",
      email: "usted@empresa.com",
      company: "Nombre de la empresa",
      phone: "(000) 000-0000",
      website: "https://",
      description: "Qué suele detenerse y qué le gustaría mejorar.",
    },
    timeIntro: "Elija un horario que le convenga para una breve llamada introductoria.",
    timeNote: "Los horarios son ilustrativos y se muestran en su zona horaria local. Confirmaremos el horario exacto por correo.",
    pickDay: "Seleccione un día",
    pickTime: "Seleccione un horario",
    consent: "Al enviar este formulario, acepta que Stellara se comunique con usted acerca de su consulta. Consulte nuestra",
    privacyLink: "Política de Privacidad",
    next: "Continuar",
    back: "Atrás",
    submit: "Solicitar este horario",
    submitting: "Enviando…",
    confirmTitle: "Solicitud recibida",
    confirmReason: "Motivo",
    confirmTime: "Horario solicitado",
    confirmEmail: "Correo de contacto",
    whatNext: "Qué esperar",
    whatNextBody:
      "Confirmaremos su horario por correo y compartiremos una breve agenda enfocada en el trabajo que describió. No requiere preparación.",
    close: "Cerrar",
    errors: {
      name: "Ingrese su nombre.",
      email: "Ingrese su correo de trabajo.",
      emailInvalid: "Ingrese un correo electrónico válido.",
      company: "Ingrese su empresa.",
      reason: "Elija un motivo para la conversación.",
      time: "Seleccione un día y un horario.",
      consent: "Acepte el consentimiento de contacto para continuar.",
    },
  },
  assistant: {
    launcherLabel: "Abrir el asistente de Stellara",
    title: "Asistente de Stellara",
    intro:
      "Hola. Puedo ayudarle a explorar dónde la automatización o el software a medida podría ser útil. ¿Dónde suele detenerse el trabajo?",
    quickReplies: [
      { id: "inquiries", label: "Llamadas perdidas" },
      { id: "followup", label: "Seguimiento de prospectos" },
      { id: "scheduling", label: "Programación de citas" },
      { id: "support", label: "Atención al cliente" },
      { id: "admin", label: "Administración repetitiva" },
      { id: "systems", label: "Sistemas desconectados" },
      { id: "unsure", label: "Otro tema" },
    ],
    followUp: "Entendido. ¿Y qué resultado es el más importante?",
    recommendPrefix: "En base a eso, un punto de partida sensato es",
    whyPrefix: "Por qué:",
    bookCta: "Abrir el agendamiento",
    restart: "Comenzar de nuevo",
    restartLabel: "Reiniciar conversación",
    closeLabel: "Cerrar asistente",
    disclaimer: "Esta es una guía interactiva, no un agente humano, y no puede acceder a datos privados de la empresa.",
    guideNote: "Demostración guiada",
  },
  footer: {
    descriptor: "Más oportunidades aprovechadas. Menos trabajo administrativo para su firma.",
    navTitle: "Explorar",
    contactTitle: "Contacto",
    contactPlaceholder: "Iniciar una conversación",
    legalTitle: "Legal",
    privacy: "Privacidad",
    terms: "Términos",
    crafted: "Concebido en el Hudson Valley.",
    rights: "Todos los derechos reservados.",
  },
  whatsapp: {
    label: "Contactar a Stellara por WhatsApp",
    message: "Hola, me interesa conocer cómo Stellara podría ayudar a automatizar un proceso en mi empresa.",
    cta: "WhatsApp",
  },
  privacy: {
    title: "Política de Privacidad",
    updated: "Última actualización",
    reviewNote: "Esta es una plantilla base. Los campos marcados para revisión requieren una revisión legal específica del negocio antes de publicarse.",
    intro:
      "Esta política explica, en lenguaje claro, cómo Stellara maneja la información compartida a través de este sitio web. Es una plantilla inicial y debe ser revisada por un asesor legal calificado antes de utilizarse.",
    sections: [
      {
        heading: "Información que recopilamos",
        body: [
          "Recopilamos la información que usted decide proporcionar mediante nuestros formularios de contacto y agendamiento, como su nombre, correo de trabajo, empresa y una descripción de su problema operativo.",
          "Podemos recopilar información técnica limitada (como eventos generales de analítica) que no incluye datos de identificación personal.",
        ],
      },
      {
        heading: "Cómo usamos la información",
        body: [
          "Usamos la información que proporciona para responder a su consulta, preparar una conversación y dar seguimiento al trabajo que describió.",
          "No vendemos su información. [Revisión: confirme los compromisos de manejo de datos con un asesor legal.]",
        ],
      },
      {
        heading: "Conservación de datos",
        body: ["[Revisión: defina los períodos de conservación apropiados para su jurisdicción y negocio.]"],
      },
      {
        heading: "Sus opciones",
        body: ["Puede solicitar acceso o eliminación de la información que compartió contactándonos. [Revisión: confirme los derechos aplicables.]"],
      },
      {
        heading: "Contacto",
        body: ["Las preguntas sobre esta política pueden dirigirse al canal de contacto indicado en este sitio."],
      },
    ],
    backHome: "Volver al inicio",
  },
  terms: {
    title: "Términos del Servicio",
    updated: "Última actualización",
    reviewNote: "Esta es una plantilla base. Los campos marcados para revisión requieren una revisión legal específica del negocio antes de publicarse.",
    intro:
      "Estos términos describen, en lenguaje claro, la base sobre la cual se ofrece este sitio web. Son una plantilla inicial y deben ser revisados por un asesor legal calificado antes de utilizarse.",
    sections: [
      {
        heading: "Uso de este sitio web",
        body: [
          "Este sitio web se ofrece con fines de información general sobre los servicios de Stellara. El contenido puede cambiar sin previo aviso.",
          "Nada en este sitio constituye una oferta vinculante, garantía o promesa de resultados específicos.",
        ],
      },
      {
        heading: "Consultas y citas",
        body: [
          "Enviar un formulario o solicitar una cita inicia una conversación y no crea un contrato de servicios.",
          "[Revisión: agregue términos de contratación, alcance y pago con un asesor legal.]",
        ],
      },
      {
        heading: "Propiedad intelectual",
        body: ["El nombre Stellara, el logotipo y los materiales de marca son propiedad de Stellara. [Revisión: confirme con un asesor legal.]"],
      },
      {
        heading: "Limitación de responsabilidad",
        body: ["[Revisión: agregue un texto de limitación de responsabilidad apropiado para su jurisdicción con un asesor legal.]"],
      },
      {
        heading: "Contacto",
        body: ["Las preguntas sobre estos términos pueden dirigirse al canal de contacto indicado en este sitio."],
      },
    ],
    backHome: "Volver al inicio",
  },
}
